import {
  NumberingSystem,
  ToothCondition,
  UserAccount,
  DepartmentQuotaRequirement,
  ClinicalCase,
  AuditLog,
  RadiographItem,
  TeachingAssistantAllocation,
  StudentGroup,
  SubjectGroupConfig,
  AcademicYearConfig,
} from '../types';

export interface ToothInfo {
  fdi: string;
  uns: string;
  palmer: string;
  nameEn: string;
  nameAr: string;
  quadrant: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8; // 1-4 permanent, 5-8 primary
  arch: 'maxillary' | 'mandibular';
  side: 'right' | 'left';
  type: 'incisor' | 'canine' | 'premolar' | 'molar';
}

// 32 Permanent Teeth
export const PERMANENT_TEETH: ToothInfo[] = [
  // Upper Right (Quadrant 1)
  { fdi: '18', uns: '1', palmer: '8┘', nameEn: 'Maxillary Right 3rd Molar', nameAr: 'رحى ثالثة علوية يمنى (عقل)', quadrant: 1, arch: 'maxillary', side: 'right', type: 'molar' },
  { fdi: '17', uns: '2', palmer: '7┘', nameEn: 'Maxillary Right 2nd Molar', nameAr: 'رحى ثانية علوية يمنى', quadrant: 1, arch: 'maxillary', side: 'right', type: 'molar' },
  { fdi: '16', uns: '3', palmer: '6┘', nameEn: 'Maxillary Right 1st Molar', nameAr: 'رحى أولى علوية يمنى', quadrant: 1, arch: 'maxillary', side: 'right', type: 'molar' },
  { fdi: '15', uns: '4', palmer: '5┘', nameEn: 'Maxillary Right 2nd Premolar', nameAr: 'ضاحك ثانٍ علوي أيمن', quadrant: 1, arch: 'maxillary', side: 'right', type: 'premolar' },
  { fdi: '14', uns: '5', palmer: '4┘', nameEn: 'Maxillary Right 1st Premolar', nameAr: 'ضاحك أول علوي أيمن', quadrant: 1, arch: 'maxillary', side: 'right', type: 'premolar' },
  { fdi: '13', uns: '6', palmer: '3┘', nameEn: 'Maxillary Right Canine', nameAr: 'ناب علوي أيمن', quadrant: 1, arch: 'maxillary', side: 'right', type: 'canine' },
  { fdi: '12', uns: '7', palmer: '2┘', nameEn: 'Maxillary Right Lateral Incisor', nameAr: 'قاطع جانبي علوي أيمن (رباعية)', quadrant: 1, arch: 'maxillary', side: 'right', type: 'incisor' },
  { fdi: '11', uns: '8', palmer: '1┘', nameEn: 'Maxillary Right Central Incisor', nameAr: 'قاطع مركزي علوي أيمن (ثنية)', quadrant: 1, arch: 'maxillary', side: 'right', type: 'incisor' },

  // Upper Left (Quadrant 2)
  { fdi: '21', uns: '9', palmer: '└1', nameEn: 'Maxillary Left Central Incisor', nameAr: 'قاطع مركزي علوي أيسر (ثنية)', quadrant: 2, arch: 'maxillary', side: 'left', type: 'incisor' },
  { fdi: '22', uns: '10', palmer: '└2', nameEn: 'Maxillary Left Lateral Incisor', nameAr: 'قاطع جانبي علوي أيسر (رباعية)', quadrant: 2, arch: 'maxillary', side: 'left', type: 'incisor' },
  { fdi: '23', uns: '11', palmer: '└3', nameEn: 'Maxillary Left Canine', nameAr: 'ناب علوي أيسر', quadrant: 2, arch: 'maxillary', side: 'left', type: 'canine' },
  { fdi: '24', uns: '12', palmer: '└4', nameEn: 'Maxillary Left 1st Premolar', nameAr: 'ضاحك أول علوي أيسر', quadrant: 2, arch: 'maxillary', side: 'left', type: 'premolar' },
  { fdi: '25', uns: '13', palmer: '└5', nameEn: 'Maxillary Left 2nd Premolar', nameAr: 'ضاحك ثانٍ علوي أيسر', quadrant: 2, arch: 'maxillary', side: 'left', type: 'premolar' },
  { fdi: '26', uns: '14', palmer: '└6', nameEn: 'Maxillary Left 1st Molar', nameAr: 'رحى أولى علوية يسرى', quadrant: 2, arch: 'maxillary', side: 'left', type: 'molar' },
  { fdi: '27', uns: '15', palmer: '└7', nameEn: 'Maxillary Left 2nd Molar', nameAr: 'رحى ثانية علوية يسرى', quadrant: 2, arch: 'maxillary', side: 'left', type: 'molar' },
  { fdi: '28', uns: '16', palmer: '└8', nameEn: 'Maxillary Left 3rd Molar', nameAr: 'رحى ثالثة علوية يسرى (عقل)', quadrant: 2, arch: 'maxillary', side: 'left', type: 'molar' },

  // Lower Left (Quadrant 3)
  { fdi: '38', uns: '17', palmer: '┌8', nameEn: 'Mandibular Left 3rd Molar', nameAr: 'رحى ثالثة سفلية يسرى (عقل)', quadrant: 3, arch: 'mandibular', side: 'left', type: 'molar' },
  { fdi: '37', uns: '18', palmer: '┌7', nameEn: 'Mandibular Left 2nd Molar', nameAr: 'رحى ثانية سفلية يسرى', quadrant: 3, arch: 'mandibular', side: 'left', type: 'molar' },
  { fdi: '36', uns: '19', palmer: '┌6', nameEn: 'Mandibular Left 1st Molar', nameAr: 'رحى أولى سفلية يسرى', quadrant: 3, arch: 'mandibular', side: 'left', type: 'molar' },
  { fdi: '35', uns: '20', palmer: '┌5', nameEn: 'Mandibular Left 2nd Premolar', nameAr: 'ضاحك ثانٍ سفلي أيسر', quadrant: 3, arch: 'mandibular', side: 'left', type: 'premolar' },
  { fdi: '34', uns: '21', palmer: '┌4', nameEn: 'Mandibular Left 1st Premolar', nameAr: 'ضاحك أول سفلي أيسر', quadrant: 3, arch: 'mandibular', side: 'left', type: 'premolar' },
  { fdi: '33', uns: '22', palmer: '┌3', nameEn: 'Mandibular Left Canine', nameAr: 'ناب سفلي أيسر', quadrant: 3, arch: 'mandibular', side: 'left', type: 'canine' },
  { fdi: '32', uns: '23', palmer: '┌2', nameEn: 'Mandibular Left Lateral Incisor', nameAr: 'قاطع جانبي سفلي أيسر (رباعية)', quadrant: 3, arch: 'mandibular', side: 'left', type: 'incisor' },
  { fdi: '31', uns: '24', palmer: '┌1', nameEn: 'Mandibular Left Central Incisor', nameAr: 'قاطع مركزي سفلي أيسر (ثنية)', quadrant: 3, arch: 'mandibular', side: 'left', type: 'incisor' },

  // Lower Right (Quadrant 4)
  { fdi: '41', uns: '25', palmer: '1┐', nameEn: 'Mandibular Right Central Incisor', nameAr: 'قاطع مركزي سفلي أيمن (ثنية)', quadrant: 4, arch: 'mandibular', side: 'right', type: 'incisor' },
  { fdi: '42', uns: '26', palmer: '2┐', nameEn: 'Mandibular Right Lateral Incisor', nameAr: 'قاطع جانبي سفلي أيمن (رباعية)', quadrant: 4, arch: 'mandibular', side: 'right', type: 'incisor' },
  { fdi: '43', uns: '27', palmer: '3┐', nameEn: 'Mandibular Right Canine', nameAr: 'ناب سفلي أيمن', quadrant: 4, arch: 'mandibular', side: 'right', type: 'canine' },
  { fdi: '44', uns: '28', palmer: '4┐', nameEn: 'Mandibular Right 1st Premolar', nameAr: 'ضاحك أول سفلي أيمن', quadrant: 4, arch: 'mandibular', side: 'right', type: 'premolar' },
  { fdi: '45', uns: '29', palmer: '5┐', nameEn: 'Mandibular Right 2nd Premolar', nameAr: 'ضاحك ثانٍ سفلي أيمن', quadrant: 4, arch: 'mandibular', side: 'right', type: 'premolar' },
  { fdi: '46', uns: '30', palmer: '6┐', nameEn: 'Mandibular Right 1st Molar', nameAr: 'رحى أولى سفلية يمنى', quadrant: 4, arch: 'mandibular', side: 'right', type: 'molar' },
  { fdi: '47', uns: '31', palmer: '7┐', nameEn: 'Mandibular Right 2nd Molar', nameAr: 'رحى ثانية سفلية يمنى', quadrant: 4, arch: 'mandibular', side: 'right', type: 'molar' },
  { fdi: '48', uns: '32', palmer: '8┐', nameEn: 'Mandibular Right 3rd Molar', nameAr: 'رحى ثالثة سفلية يمنى (عقل)', quadrant: 4, arch: 'mandibular', side: 'right', type: 'molar' },
];

// 20 Deciduous / Primary Teeth (Pediatric)
export const DECIDUOUS_TEETH: ToothInfo[] = [
  // Upper Right (Quadrant 5)
  { fdi: '55', uns: 'A', palmer: 'E┘', nameEn: 'Primary Maxillary Right 2nd Molar', nameAr: 'رحى ثانية لبنية علوية يمنى', quadrant: 5, arch: 'maxillary', side: 'right', type: 'molar' },
  { fdi: '54', uns: 'B', palmer: 'D┘', nameEn: 'Primary Maxillary Right 1st Molar', nameAr: 'رحى أولى لبنية علوية يمنى', quadrant: 5, arch: 'maxillary', side: 'right', type: 'molar' },
  { fdi: '53', uns: 'C', palmer: 'C┘', nameEn: 'Primary Maxillary Right Canine', nameAr: 'ناب لبني علوي أيمن', quadrant: 5, arch: 'maxillary', side: 'right', type: 'canine' },
  { fdi: '52', uns: 'D', palmer: 'B┘', nameEn: 'Primary Maxillary Right Lateral Incisor', nameAr: 'قاطع جانبي لبني علوي أيمن', quadrant: 5, arch: 'maxillary', side: 'right', type: 'incisor' },
  { fdi: '51', uns: 'E', palmer: 'A┘', nameEn: 'Primary Maxillary Right Central Incisor', nameAr: 'قاطع مركزي لبني علوي أيمن', quadrant: 5, arch: 'maxillary', side: 'right', type: 'incisor' },

  // Upper Left (Quadrant 6)
  { fdi: '61', uns: 'F', palmer: '└A', nameEn: 'Primary Maxillary Left Central Incisor', nameAr: 'قاطع مركزي لبني علوي أيسر', quadrant: 6, arch: 'maxillary', side: 'left', type: 'incisor' },
  { fdi: '62', uns: 'G', palmer: '└B', nameEn: 'Primary Maxillary Left Lateral Incisor', nameAr: 'قاطع جانبي لبني علوي أيسر', quadrant: 6, arch: 'maxillary', side: 'left', type: 'incisor' },
  { fdi: '63', uns: 'H', palmer: '└C', nameEn: 'Primary Maxillary Left Canine', nameAr: 'ناب لبني علوي أيسر', quadrant: 6, arch: 'maxillary', side: 'left', type: 'canine' },
  { fdi: '64', uns: 'I', palmer: '└D', nameEn: 'Primary Maxillary Left 1st Molar', nameAr: 'رحى أولى لبنية علوية يسرى', quadrant: 6, arch: 'maxillary', side: 'left', type: 'molar' },
  { fdi: '65', uns: 'J', palmer: '└E', nameEn: 'Primary Maxillary Left 2nd Molar', nameAr: 'رحى ثانية لبنية علوية يسرى', quadrant: 6, arch: 'maxillary', side: 'left', type: 'molar' },

  // Lower Left (Quadrant 7)
  { fdi: '75', uns: 'K', palmer: '┌E', nameEn: 'Primary Mandibular Left 2nd Molar', nameAr: 'رحى ثانية لبنية سفلية يسرى', quadrant: 7, arch: 'mandibular', side: 'left', type: 'molar' },
  { fdi: '74', uns: 'L', palmer: '┌D', nameEn: 'Primary Mandibular Left 1st Molar', nameAr: 'رحى أولى لبنية سفلية يسرى', quadrant: 7, arch: 'mandibular', side: 'left', type: 'molar' },
  { fdi: '73', uns: 'M', palmer: '┌C', nameEn: 'Primary Mandibular Left Canine', nameAr: 'ناب لبني سفلي أيسر', quadrant: 7, arch: 'mandibular', side: 'left', type: 'canine' },
  { fdi: '72', uns: 'N', palmer: '┌B', nameEn: 'Primary Mandibular Left Lateral Incisor', nameAr: 'قاطع جانبي لبني سفلي أيسر', quadrant: 7, arch: 'mandibular', side: 'left', type: 'incisor' },
  { fdi: '71', uns: 'O', palmer: '┌A', nameEn: 'Primary Mandibular Left Central Incisor', nameAr: 'قاطع مركزي لبني سفلي أيسر', quadrant: 7, arch: 'mandibular', side: 'left', type: 'incisor' },

  // Lower Right (Quadrant 8)
  { fdi: '81', uns: 'P', palmer: 'A┐', nameEn: 'Primary Mandibular Right Central Incisor', nameAr: 'قاطع مركزي لبني سفلي أيمن', quadrant: 8, arch: 'mandibular', side: 'right', type: 'incisor' },
  { fdi: '82', uns: 'Q', palmer: 'B┐', nameEn: 'Primary Mandibular Right Lateral Incisor', nameAr: 'قاطع جانبي لبني سفلي أيمن', quadrant: 8, arch: 'mandibular', side: 'right', type: 'incisor' },
  { fdi: '83', uns: 'R', palmer: 'C┐', nameEn: 'Primary Mandibular Right Canine', nameAr: 'ناب لبني سفلي أيمن', quadrant: 8, arch: 'mandibular', side: 'right', type: 'canine' },
  { fdi: '84', uns: 'S', palmer: 'D┐', nameEn: 'Primary Mandibular Right 1st Molar', nameAr: 'رحى أولى لبنية سفلية يمنى', quadrant: 8, arch: 'mandibular', side: 'right', type: 'molar' },
  { fdi: '85', uns: 'T', palmer: 'E┐', nameEn: 'Primary Mandibular Right 2nd Molar', nameAr: 'رحى ثانية لبنية سفلية يمنى', quadrant: 8, arch: 'mandibular', side: 'right', type: 'molar' },
];

export function getToothLabel(tooth: ToothInfo, system: NumberingSystem): string {
  switch (system) {
    case 'fdi':
      return tooth.fdi;
    case 'uns':
      return tooth.uns;
    case 'palmer':
      return tooth.palmer;
  }
}

export const CONDITION_CONFIG: Record<
  ToothCondition,
  { labelAr: string; labelEn: string; color: string; bgBadge: string; border: string }
> = {
  sound: {
    labelAr: 'سليم',
    labelEn: 'Sound',
    color: '#10b981', // emerald-500
    bgBadge: 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800',
    border: '#10b981',
  },
  caries: {
    labelAr: 'نخر تسوس',
    labelEn: 'Caries',
    color: '#ef4444', // red-500
    bgBadge: 'bg-red-50 text-red-700 dark:bg-red-950/50 dark:text-red-300 border-red-200 dark:border-red-800',
    border: '#ef4444',
  },
  filling_composite: {
    labelAr: 'حشوة كمبوزيت',
    labelEn: 'Composite Filling',
    color: '#3b82f6', // blue-500
    bgBadge: 'bg-blue-50 text-blue-700 dark:bg-blue-950/50 dark:text-blue-300 border-blue-200 dark:border-blue-800',
    border: '#3b82f6',
  },
  filling_amalgam: {
    labelAr: 'حشوة أملغم فضية',
    labelEn: 'Amalgam Filling',
    color: '#64748b', // slate-500
    bgBadge: 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300 border-slate-300 dark:border-slate-700',
    border: '#64748b',
  },
  endo_rct: {
    labelAr: 'معالجة لبية (عصب)',
    labelEn: 'Endo / RCT',
    color: '#8b5cf6', // purple-500
    bgBadge: 'bg-purple-50 text-purple-700 dark:bg-purple-950/50 dark:text-purple-300 border-purple-200 dark:border-purple-800',
    border: '#8b5cf6',
  },
  crown: {
    labelAr: 'تاج وخزف',
    labelEn: 'Crown / Cap',
    color: '#f59e0b', // amber-500
    bgBadge: 'bg-amber-50 text-amber-700 dark:bg-amber-950/50 dark:text-amber-300 border-amber-200 dark:border-amber-800',
    border: '#f59e0b',
  },
  extraction: {
    labelAr: 'مخلوع / خلع',
    labelEn: 'Extracted / Indicated',
    color: '#dc2626', // red-600
    bgBadge: 'bg-rose-50 text-rose-700 dark:bg-rose-950/50 dark:text-rose-300 border-rose-200 dark:border-rose-800',
    border: '#dc2626',
  },
  missing: {
    labelAr: 'مفقود خلقياً أو سريرياً',
    labelEn: 'Missing Tooth',
    color: '#94a3b8', // slate-400
    bgBadge: 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300 border-slate-300 dark:border-slate-700',
    border: '#94a3b8',
  },
  bridge: {
    labelAr: 'جسر سني',
    labelEn: 'Bridge Pontic',
    color: '#06b6d4', // cyan-500
    bgBadge: 'bg-cyan-50 text-cyan-700 dark:bg-cyan-950/50 dark:text-cyan-300 border-cyan-200 dark:border-cyan-800',
    border: '#06b6d4',
  },
  implant: {
    labelAr: 'زراعة سنية',
    labelEn: 'Implant',
    color: '#0d9488', // teal-600
    bgBadge: 'bg-teal-50 text-teal-700 dark:bg-teal-950/50 dark:text-teal-300 border-teal-200 dark:border-teal-800',
    border: '#0d9488',
  },
  ortho: {
    labelAr: 'جهاز تقويم',
    labelEn: 'Ortho Appliance',
    color: '#ec4899', // pink-500
    bgBadge: 'bg-pink-50 text-pink-700 dark:bg-pink-950/50 dark:text-pink-300 border-pink-200 dark:border-pink-800',
    border: '#ec4899',
  },
};

// Default Sample High-Resolution Radiographs (Using reliable SVG visual representations of dental findings)
export const SAMPLE_RADIOGRAPHS: RadiographItem[] = [
  {
    id: 'rad-1',
    title: 'OPG - بانوراما الفكين الشاملة',
    type: 'panoramic',
    date: '2026-08-15',
    url: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=1200&q=80',
    notes: 'بانوراما رقمية توضح انطمار الأرحاء الثالثة وتكلس قنوات السن 46 مع غياب آفات ذروية واضحة.',
  },
  {
    id: 'rad-2',
    title: 'Periapical - أشعة ذروية للسن 46 (عصب)',
    type: 'periapical',
    toothNumber: '46',
    date: '2026-08-20',
    url: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
    notes: 'أشعة ذروية مع قياس الطول العامل (Working Length) للقنوات الإنسية والوحشية.',
  },
  {
    id: 'rad-3',
    title: 'Bitewing - أشعة مجنحة لتشخيص التسوس الملاصق',
    type: 'bitewing',
    toothNumber: '15, 16',
    date: '2026-08-22',
    url: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=800&q=80',
    notes: 'تسوس ملاصق بالسطح الإنسي للسن 16 وتآكل في الميناء والعاج.',
  },
  {
    id: 'rad-4',
    title: 'CBCT - مقطع ثلاثي الأبعاد لتخطيط الزرع السني',
    type: 'cbct',
    toothNumber: '36',
    date: '2026-08-28',
    url: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=800&q=80',
    notes: 'قياس الكثافة العظمية والمسافة عن القناة السنخية السفلية لوضع زرعة 4.2x10mm.',
  },
];

// Default Department Quota Requirements (Standard Dental Faculty Requirements)
export const DEFAULT_QUOTAS: DepartmentQuotaRequirement[] = [
  {
    department: 'operative',
    departmentNameAr: 'طب الأسنان التحفظي والحشوات',
    departmentNameEn: 'Operative Dentistry & Restorations',
    requiredUnits: 20,
    descriptionAr: 'يشمل حشوات الكمبوزيت، الأملغم، والترميمات المباشرة Class I & Class II',
    descriptionEn: 'Includes Class I & II Composite/Amalgam Direct Restorations',
  },
  {
    department: 'endodontics',
    departmentNameAr: 'علاج الجذور وعصب الأسنان',
    departmentNameEn: 'Endodontics (Root Canal Treatment)',
    requiredUnits: 8,
    descriptionAr: 'معالجة لبية كاملة للأسنان الأمامية، الضواحك، والأرحاء متعددة القنوات',
    descriptionEn: 'Complete endodontic therapy for anterior, premolar and multi-canal molars',
  },
  {
    department: 'prosthodontics',
    departmentNameAr: 'الاستعاضة الصناعية والتركيبات',
    departmentNameEn: 'Prosthodontics',
    requiredUnits: 6,
    descriptionAr: 'أطقم متحركة جزئية/كاملة، وتيجان وخزف مفردة وجسور سنية',
    descriptionEn: 'Complete/Partial Dentures, Single Crowns and Fixed Bridges',
  },
  {
    department: 'periodontics',
    departmentNameAr: 'طب وجراحة اللثة والأنسجة المحيطة',
    departmentNameEn: 'Periodontics',
    requiredUnits: 12,
    descriptionAr: 'تقليح وتجريف الجذور، معالجة الجيوب اللثوية، وتوجيه العناية الفموية',
    descriptionEn: 'Scaling and root planing, subgingival curettage, and oral hygiene instruction',
  },
  {
    department: 'pedodontics',
    departmentNameAr: 'طب أسنان الأطفال',
    departmentNameEn: 'Pediatric Dentistry',
    requiredUnits: 10,
    descriptionAr: 'حشوات الأسنان اللبنية، بتر اللب Pulpotomy، وتيجان الستانلس ستيل SSC',
    descriptionEn: 'Deciduous restorations, Pulpotomy, Stainless Steel Crowns & space maintainers',
  },
  {
    department: 'oral_surgery',
    departmentNameAr: 'جراحة الفم والوجه والفكين',
    departmentNameEn: 'Oral & Maxillofacial Surgery',
    requiredUnits: 15,
    descriptionAr: 'خلع جراحي وغير جراحي، وتخدير موضعي، وتدبير النزف بعد الخلع',
    descriptionEn: 'Simple & Surgical extractions, local anesthesia techniques & suturing',
  },
  {
    department: 'orthodontics',
    departmentNameAr: 'تقويم الأسنان والفكين',
    departmentNameEn: 'Orthodontics',
    requiredUnits: 4,
    descriptionAr: 'تشخيص حالات الإطباق، دراسة النماذج الجبسية، والأجهزة الوقائية والمتحركة',
    descriptionEn: 'Cephalometric tracing, study models analysis & interceptive appliances',
  },
];

// Academic Years Seed
export const SEED_ACADEMIC_YEARS: AcademicYearConfig[] = [
  { id: 'year-2025-2026', yearLabel: '2025-2026', isCurrent: true, startDate: '2025-09-01', endDate: '2026-06-30' },
  { id: 'year-2024-2025', yearLabel: '2024-2025', isCurrent: false, startDate: '2024-09-01', endDate: '2025-06-30' },
  { id: 'year-2026-2027', yearLabel: '2026-2027', isCurrent: false, startDate: '2026-09-01', endDate: '2027-06-30' },
];

// Student Clinical Groups Seed
export const SEED_STUDENT_GROUPS: StudentGroup[] = [
  // 4th Year Groups
  { id: 'grp-l4-a1', code: 'Group A1', nameAr: 'المجموعة A1 (العيادة 1)', academicLevel: 'level4', academicYear: '2025-2026', clinicRoom: 'عيادة 1' },
  { id: 'grp-l4-a2', code: 'Group A2', nameAr: 'المجموعة A2 (العيادة 2)', academicLevel: 'level4', academicYear: '2025-2026', clinicRoom: 'عيادة 2' },
  { id: 'grp-l4-b1', code: 'Group B1', nameAr: 'المجموعة B1 (العيادة 3)', academicLevel: 'level4', academicYear: '2025-2026', clinicRoom: 'عيادة 3' },
  { id: 'grp-l4-b2', code: 'Group B2', nameAr: 'المجموعة B2 (العيادة 4)', academicLevel: 'level4', academicYear: '2025-2026', clinicRoom: 'عيادة 4' },

  // 5th Year Groups
  { id: 'grp-l5-a1', code: 'Group A1', nameAr: 'المجموعة A1 (العيادة 1)', academicLevel: 'level5', academicYear: '2025-2026', clinicRoom: 'عيادة 1' },
  { id: 'grp-l5-a2', code: 'Group A2', nameAr: 'المجموعة A2 (العيادة 2)', academicLevel: 'level5', academicYear: '2025-2026', clinicRoom: 'عيادة 2' },
  { id: 'grp-l5-b1', code: 'Group B1', nameAr: 'المجموعة B1 (العيادة 3)', academicLevel: 'level5', academicYear: '2025-2026', clinicRoom: 'عيادة 3' },
  { id: 'grp-l5-b2', code: 'Group B2', nameAr: 'المجموعة B2 (العيادة 4)', academicLevel: 'level5', academicYear: '2025-2026', clinicRoom: 'عيادة 4' },
];

// Seed Subject-Specific Student Groups (تقسيم الطلاب حسب المستويات والمجموعات لكل مادة)
export const SEED_SUBJECT_GROUPS: SubjectGroupConfig[] = [
  // ===================== Level 4 - Semester 1 =====================
  // Operative Dentistry (Level 4 Sem 1)
  {
    id: 'sgrp-l4-s1-op-a1',
    academicLevel: 'level4',
    semester: 'first',
    academicYear: '2025-2026',
    subjectId: 'operative',
    subjectNameAr: 'العلاج التحفظي وإصلاح الأسنان',
    subjectNameEn: 'Operative Dentistry',
    code: 'Group A1',
    nameAr: 'مجموعة A1 (عيادة الحشوات 1)',
    clinicRoom: 'عيادة 1',
    scheduleDayTime: 'الأحد: 08:30 ص - 11:30 ص',
    assignedTaId: 'user-ta-1',
    assignedTaName: 'د. عمر باوزير',
    assignedSupervisorId: 'user-dept-head-1',
    assignedSupervisorName: 'د. طارق السعيد',
    maxCapacity: 10,
    studentIds: ['user-student-5', 'user-student-3'],
    notes: 'التركيز على حشوات الصنف الأول والثاني مع الأملغم والكمبوزيت',
  },
  {
    id: 'sgrp-l4-s1-op-a2',
    academicLevel: 'level4',
    semester: 'first',
    academicYear: '2025-2026',
    subjectId: 'operative',
    subjectNameAr: 'العلاج التحفظي وإصلاح الأسنان',
    subjectNameEn: 'Operative Dentistry',
    code: 'Group A2',
    nameAr: 'مجموعة A2 (عيادة الحشوات 2)',
    clinicRoom: 'عيادة 2',
    scheduleDayTime: 'الأحد: 11:30 ص - 02:30 م',
    assignedTaId: 'user-ta-1',
    assignedTaName: 'د. عمر باوزير',
    assignedSupervisorId: 'user-dept-head-1',
    assignedSupervisorName: 'د. طارق السعيد',
    maxCapacity: 10,
    studentIds: ['user-student-6'],
    notes: 'جلسة تدريب سريري ثانية',
  },
  {
    id: 'sgrp-l4-s1-op-b1',
    academicLevel: 'level4',
    semester: 'first',
    academicYear: '2025-2026',
    subjectId: 'operative',
    subjectNameAr: 'العلاج التحفظي وإصلاح الأسنان',
    subjectNameEn: 'Operative Dentistry',
    code: 'Group B1',
    nameAr: 'مجموعة B1 (عيادة الحشوات 3)',
    clinicRoom: 'عيادة 3',
    scheduleDayTime: 'الثلاثاء: 08:30 ص - 11:30 ص',
    assignedTaId: 'user-ta-4',
    assignedTaName: 'د. منى الكاف',
    maxCapacity: 10,
    studentIds: [],
  },

  // Endodontics (Level 4 Sem 1)
  {
    id: 'sgrp-l4-s1-endo-a1',
    academicLevel: 'level4',
    semester: 'first',
    academicYear: '2025-2026',
    subjectId: 'endodontics',
    subjectNameAr: 'علاج جذور الأسنان',
    subjectNameEn: 'Endodontics',
    code: 'Group A1',
    nameAr: 'مجموعة A1 (عيادة الجذور 1)',
    clinicRoom: 'عيادة 1',
    scheduleDayTime: 'الإثنين: 08:30 ص - 11:30 ص',
    assignedTaId: 'user-ta-2',
    assignedTaName: 'د. ياسمين النعمان',
    assignedSupervisorId: 'user-supervisor-1',
    assignedSupervisorName: 'د. سارة الشمري',
    maxCapacity: 8,
    studentIds: ['user-student-3', 'user-student-5'],
    notes: 'معالجة أسنان أمامية وضواحك',
  },
  {
    id: 'sgrp-l4-s1-endo-a2',
    academicLevel: 'level4',
    semester: 'first',
    academicYear: '2025-2026',
    subjectId: 'endodontics',
    subjectNameAr: 'علاج جذور الأسنان',
    subjectNameEn: 'Endodontics',
    code: 'Group A2',
    nameAr: 'مجموعة A2 (عيادة الجذور 2)',
    clinicRoom: 'عيادة 2',
    scheduleDayTime: 'الإثنين: 11:30 ص - 02:30 م',
    assignedTaId: 'user-ta-2',
    assignedTaName: 'د. ياسمين النعمان',
    assignedSupervisorId: 'user-supervisor-1',
    assignedSupervisorName: 'د. سارة الشمري',
    maxCapacity: 8,
    studentIds: ['user-student-6'],
  },

  // Fixed Prosthodontics (Level 4 Sem 1)
  {
    id: 'sgrp-l4-s1-pros-a1',
    academicLevel: 'level4',
    semester: 'first',
    academicYear: '2025-2026',
    subjectId: 'prosthodontics',
    subjectNameAr: 'الاستعاضة السنية الثابتة',
    subjectNameEn: 'Fixed Prosthodontics',
    code: 'Group A1',
    nameAr: 'مجموعة A1 (عيادة التركيبات 1)',
    clinicRoom: 'عيادة 1',
    scheduleDayTime: 'الأربعاء: 08:30 ص - 11:30 ص',
    assignedTaId: 'user-ta-3',
    assignedTaName: 'د. فيصل السالم',
    maxCapacity: 8,
    studentIds: ['user-student-5'],
    notes: 'تيجان وجسور خلفية',
  },
  {
    id: 'sgrp-l4-s1-pros-a2',
    academicLevel: 'level4',
    semester: 'first',
    academicYear: '2025-2026',
    subjectId: 'prosthodontics',
    subjectNameAr: 'الاستعاضة السنية الثابتة',
    subjectNameEn: 'Fixed Prosthodontics',
    code: 'Group A2',
    nameAr: 'مجموعة A2 (عيادة التركيبات 2)',
    clinicRoom: 'عيادة 2',
    scheduleDayTime: 'الأربعاء: 11:30 ص - 02:30 م',
    assignedTaId: 'user-ta-3',
    assignedTaName: 'د. فيصل السالم',
    maxCapacity: 8,
    studentIds: ['user-student-3', 'user-student-6'],
  },

  // ===================== Level 5 - Semester 1 =====================
  // Operative Dentistry (Level 5 Sem 1)
  {
    id: 'sgrp-l5-s1-op-a1',
    academicLevel: 'level5',
    semester: 'first',
    academicYear: '2025-2026',
    subjectId: 'operative',
    subjectNameAr: 'العلاج التحفظي المتقدم',
    subjectNameEn: 'Advanced Operative Dentistry',
    code: 'Group A1',
    nameAr: 'مجموعة A1 (العيادة التحفظية الشاملة 1)',
    clinicRoom: 'عيادة 1',
    scheduleDayTime: 'الأحد: 08:00 ص - 12:00 م',
    assignedTaId: 'user-ta-1',
    assignedTaName: 'د. عمر باوزير',
    assignedSupervisorId: 'user-dept-head-1',
    assignedSupervisorName: 'د. طارق السعيد',
    maxCapacity: 12,
    studentIds: ['user-student-1', 'user-student-2'],
    notes: 'حالات معقدة وترميم تيجان وبناء أوتاد فايبر',
  },
  {
    id: 'sgrp-l5-s1-op-a2',
    academicLevel: 'level5',
    semester: 'first',
    academicYear: '2025-2026',
    subjectId: 'operative',
    subjectNameAr: 'العلاج التحفظي المتقدم',
    subjectNameEn: 'Advanced Operative Dentistry',
    code: 'Group A2',
    nameAr: 'مجموعة A2 (العيادة التحفظية الشاملة 2)',
    clinicRoom: 'عيادة 2',
    scheduleDayTime: 'الأحد: 01:00 م - 04:30 م',
    assignedTaId: 'user-ta-1',
    assignedTaName: 'د. عمر باوزير',
    assignedSupervisorId: 'user-dept-head-1',
    assignedSupervisorName: 'د. طارق السعيد',
    maxCapacity: 12,
    studentIds: ['user-student-4'],
  },

  // Endodontics (Level 5 Sem 1)
  {
    id: 'sgrp-l5-s1-endo-a1',
    academicLevel: 'level5',
    semester: 'first',
    academicYear: '2025-2026',
    subjectId: 'endodontics',
    subjectNameAr: 'علاج جذور الأسنان المتقدم',
    subjectNameEn: 'Advanced Endodontics',
    code: 'Group A1',
    nameAr: 'مجموعة A1 (عيادة عصب الأرحاء 1)',
    clinicRoom: 'عيادة 1',
    scheduleDayTime: 'الإثنين: 08:00 ص - 12:00 م',
    assignedTaId: 'user-ta-2',
    assignedTaName: 'د. ياسمين النعمان',
    assignedSupervisorId: 'user-supervisor-1',
    assignedSupervisorName: 'د. سارة الشمري',
    maxCapacity: 8,
    studentIds: ['user-student-1', 'user-student-4'],
    notes: 'معالجة أرحاء وضواحك علوية وسفلية',
  },
  {
    id: 'sgrp-l5-s1-endo-a2',
    academicLevel: 'level5',
    semester: 'first',
    academicYear: '2025-2026',
    subjectId: 'endodontics',
    subjectNameAr: 'علاج جذور الأسنان المتقدم',
    subjectNameEn: 'Advanced Endodontics',
    code: 'Group A2',
    nameAr: 'مجموعة A2 (عيادة عصب الأرحاء 2)',
    clinicRoom: 'عيادة 2',
    scheduleDayTime: 'الإثنين: 01:00 م - 04:30 م',
    assignedTaId: 'user-ta-2',
    assignedTaName: 'د. ياسمين النعمان',
    assignedSupervisorId: 'user-supervisor-1',
    assignedSupervisorName: 'د. سارة الشمري',
    maxCapacity: 8,
    studentIds: ['user-student-2'],
  },

  // Oral Surgery (Level 5 Sem 1)
  {
    id: 'sgrp-l5-s1-surg-a1',
    academicLevel: 'level5',
    semester: 'first',
    academicYear: '2025-2026',
    subjectId: 'oral_surgery',
    subjectNameAr: 'جراحة الفم والوجه والفكين',
    subjectNameEn: 'Oral Surgery',
    code: 'Group A1',
    nameAr: 'مجموعة A1 (عيادة جراحة الفم والخلع الجراحي)',
    clinicRoom: 'عيادة جراحة 1',
    scheduleDayTime: 'الخميس: 08:00 ص - 12:00 م',
    assignedTaId: 'user-ta-6',
    assignedTaName: 'د. طارق باعباد',
    assignedSupervisorId: 'user-supervisor-2',
    assignedSupervisorName: 'د. فهد القحطاني',
    maxCapacity: 10,
    studentIds: ['user-student-1', 'user-student-2'],
    notes: 'خلع جراحي وبسيط وتخدير موضعي جراحي',
  },
  {
    id: 'sgrp-l5-s1-surg-a2',
    academicLevel: 'level5',
    semester: 'first',
    academicYear: '2025-2026',
    subjectId: 'oral_surgery',
    subjectNameAr: 'جراحة الفم والوجه والفكين',
    subjectNameEn: 'Oral Surgery',
    code: 'Group A2',
    nameAr: 'مجموعة A2 (عيادة جراحة الفم 2)',
    clinicRoom: 'عيادة جراحة 2',
    scheduleDayTime: 'الخميس: 01:00 م - 04:30 م',
    assignedTaId: 'user-ta-6',
    assignedTaName: 'د. طارق باعباد',
    assignedSupervisorId: 'user-supervisor-2',
    assignedSupervisorName: 'د. فهد القحطاني',
    maxCapacity: 10,
    studentIds: ['user-student-4'],
  },

  // Pediatric Dentistry (Level 5 Sem 1)
  {
    id: 'sgrp-l5-s1-pedo-a1',
    academicLevel: 'level5',
    semester: 'first',
    academicYear: '2025-2026',
    subjectId: 'pedodontics',
    subjectNameAr: 'طب أسنان الأطفال',
    subjectNameEn: 'Pediatric Dentistry',
    code: 'Group A1',
    nameAr: 'مجموعة A1 (عيادة أسنان الأطفال)',
    clinicRoom: 'عيادة أطفال 1',
    scheduleDayTime: 'الأربعاء: 08:00 ص - 12:00 م',
    assignedTaId: 'user-ta-4',
    assignedTaName: 'د. منى الكاف',
    maxCapacity: 10,
    studentIds: ['user-student-1', 'user-student-2', 'user-student-4'],
    notes: 'بتر اللب وتيجان الستانلس ستيل وحشوات الأطفال',
  },

  // Periodontics (Level 5 Sem 1)
  {
    id: 'sgrp-l5-s1-perio-a1',
    academicLevel: 'level5',
    semester: 'first',
    academicYear: '2025-2026',
    subjectId: 'periodontics',
    subjectNameAr: 'أمراض وجراحة اللثة',
    subjectNameEn: 'Periodontics',
    code: 'Group A1',
    nameAr: 'مجموعة A1 (عيادة علاج اللثة والتقليح)',
    clinicRoom: 'عيادة لثة 1',
    scheduleDayTime: 'الأربعاء: 01:00 م - 04:30 م',
    assignedTaId: 'user-ta-5',
    assignedTaName: 'د. خالد اليافعي',
    maxCapacity: 10,
    studentIds: ['user-student-1', 'user-student-4'],
    notes: 'تنظيف عميق، كشط الجذور وتسوية السطح',
  },
  {
    id: 'sgrp-l5-s1-perio-a2',
    academicLevel: 'level5',
    semester: 'first',
    academicYear: '2025-2026',
    subjectId: 'periodontics',
    subjectNameAr: 'أمراض وجراحة اللثة',
    subjectNameEn: 'Periodontics',
    code: 'Group A2',
    nameAr: 'مجموعة A2 (عيادة اللثة 2)',
    clinicRoom: 'عيادة لثة 2',
    scheduleDayTime: 'الأربعاء: 01:00 م - 04:30 م',
    assignedTaId: 'user-ta-5',
    assignedTaName: 'د. خالد اليافعي',
    maxCapacity: 10,
    studentIds: ['user-student-2'],
  },

  // Prosthodontics (Level 5 Sem 1)
  {
    id: 'sgrp-l5-s1-pros-a1',
    academicLevel: 'level5',
    semester: 'first',
    academicYear: '2025-2026',
    subjectId: 'prosthodontics',
    subjectNameAr: 'الاستعاضة والتركيبات السنية',
    subjectNameEn: 'Prosthodontics',
    code: 'Group A1',
    nameAr: 'مجموعة A1 (عيادة التركيبات المتحركة والثابتة)',
    clinicRoom: 'عيادة تركيبات 1',
    scheduleDayTime: 'الثلاثاء: 08:00 ص - 12:00 م',
    assignedTaId: 'user-ta-3',
    assignedTaName: 'د. فيصل السالم',
    maxCapacity: 8,
    studentIds: ['user-student-1'],
    notes: 'أطقم جزئية وتيجان منفصلة',
  },
  {
    id: 'sgrp-l5-s1-pros-a2',
    academicLevel: 'level5',
    semester: 'first',
    academicYear: '2025-2026',
    subjectId: 'prosthodontics',
    subjectNameAr: 'الاستعاضة والتركيبات السنية',
    subjectNameEn: 'Prosthodontics',
    code: 'Group A2',
    nameAr: 'مجموعة A2 (عيادة التركيبات 2)',
    clinicRoom: 'عيادة تركيبات 2',
    scheduleDayTime: 'الثلاثاء: 01:00 م - 04:30 م',
    assignedTaId: 'user-ta-3',
    assignedTaName: 'د. فيصل السالم',
    maxCapacity: 8,
    studentIds: ['user-student-2', 'user-student-4'],
  },
];

// Teaching Assistant Relational Allocation Matrix (Level + Semester + Subject + Group ➔ TA)
export const SEED_TA_ALLOCATIONS: TeachingAssistantAllocation[] = [
  // ===================== Level 4 - Semester 1 =====================
  // Operative Dentistry
  { id: 'alc-1', taId: 'user-ta-1', taName: 'د. عمر باوزير', academicYear: '2025-2026', academicLevel: 'level4', semester: 'first', subjectId: 'operative', subjectNameAr: 'العلاج التحفظي (Operative)', subjectNameEn: 'Operative Dentistry', groupCode: 'Group A1', clinicRoom: 'عيادة 1', quotaTargetCases: 11 },
  { id: 'alc-2', taId: 'user-ta-1', taName: 'د. عمر باوزير', academicYear: '2025-2026', academicLevel: 'level4', semester: 'first', subjectId: 'operative', subjectNameAr: 'العلاج التحفظي (Operative)', subjectNameEn: 'Operative Dentistry', groupCode: 'Group A2', clinicRoom: 'عيادة 2', quotaTargetCases: 11 },
  { id: 'alc-3', taId: 'user-ta-4', taName: 'د. منى الكاف', academicYear: '2025-2026', academicLevel: 'level4', semester: 'first', subjectId: 'operative', subjectNameAr: 'العلاج التحفظي (Operative)', subjectNameEn: 'Operative Dentistry', groupCode: 'Group B1', clinicRoom: 'عيادة 3', quotaTargetCases: 11 },
  { id: 'alc-4', taId: 'user-ta-4', taName: 'د. منى الكاف', academicYear: '2025-2026', academicLevel: 'level4', semester: 'first', subjectId: 'operative', subjectNameAr: 'العلاج التحفظي (Operative)', subjectNameEn: 'Operative Dentistry', groupCode: 'Group B2', clinicRoom: 'عيادة 4', quotaTargetCases: 11 },

  // Endodontics
  { id: 'alc-5', taId: 'user-ta-2', taName: 'د. ياسمين النعمان', academicYear: '2025-2026', academicLevel: 'level4', semester: 'first', subjectId: 'endodontics', subjectNameAr: 'علاج الجذور (Endodontics)', subjectNameEn: 'Endodontics', groupCode: 'Group A1', clinicRoom: 'عيادة 1', quotaTargetCases: 6 },
  { id: 'alc-6', taId: 'user-ta-2', taName: 'د. ياسمين النعمان', academicYear: '2025-2026', academicLevel: 'level4', semester: 'first', subjectId: 'endodontics', subjectNameAr: 'علاج الجذور (Endodontics)', subjectNameEn: 'Endodontics', groupCode: 'Group A2', clinicRoom: 'عيادة 2', quotaTargetCases: 6 },
  { id: 'alc-7', taId: 'user-ta-1', taName: 'د. عمر باوزير', academicYear: '2025-2026', academicLevel: 'level4', semester: 'first', subjectId: 'endodontics', subjectNameAr: 'علاج الجذور (Endodontics)', subjectNameEn: 'Endodontics', groupCode: 'Group B1', clinicRoom: 'عيادة 3', quotaTargetCases: 6 },
  { id: 'alc-8', taId: 'user-ta-1', taName: 'د. عمر باوزير', academicYear: '2025-2026', academicLevel: 'level4', semester: 'first', subjectId: 'endodontics', subjectNameAr: 'علاج الجذور (Endodontics)', subjectNameEn: 'Endodontics', groupCode: 'Group B2', clinicRoom: 'عيادة 4', quotaTargetCases: 6 },

  // Fixed Prosthodontics
  { id: 'alc-9', taId: 'user-ta-3', taName: 'د. فيصل السالم', academicYear: '2025-2026', academicLevel: 'level4', semester: 'first', subjectId: 'prosthodontics', subjectNameAr: 'الاستعاضة السنية الثابتة (Fixed Prostho)', subjectNameEn: 'Fixed Prosthodontics', groupCode: 'Group A1', clinicRoom: 'عيادة 1', quotaTargetCases: 6 },
  { id: 'alc-10', taId: 'user-ta-3', taName: 'د. فيصل السالم', academicYear: '2025-2026', academicLevel: 'level4', semester: 'first', subjectId: 'prosthodontics', subjectNameAr: 'الاستعاضة السنية الثابتة (Fixed Prostho)', subjectNameEn: 'Fixed Prosthodontics', groupCode: 'Group A2', clinicRoom: 'عيادة 2', quotaTargetCases: 6 },
  { id: 'alc-11', taId: 'user-ta-3', taName: 'د. فيصل السالم', academicYear: '2025-2026', academicLevel: 'level4', semester: 'first', subjectId: 'prosthodontics', subjectNameAr: 'الاستعاضة السنية الثابتة (Fixed Prostho)', subjectNameEn: 'Fixed Prosthodontics', groupCode: 'Group B1', clinicRoom: 'عيادة 3', quotaTargetCases: 6 },
  { id: 'alc-12', taId: 'user-ta-3', taName: 'د. فيصل السالم', academicYear: '2025-2026', academicLevel: 'level4', semester: 'first', subjectId: 'prosthodontics', subjectNameAr: 'الاستعاضة السنية الثابتة (Fixed Prostho)', subjectNameEn: 'Fixed Prosthodontics', groupCode: 'Group B2', clinicRoom: 'عيادة 4', quotaTargetCases: 6 },

  // ===================== Level 4 - Semester 2 =====================
  // Periodontics (4th Year Sem 2)
  { id: 'alc-13', taId: 'user-ta-5', taName: 'د. خالد اليافعي', academicYear: '2025-2026', academicLevel: 'level4', semester: 'second', subjectId: 'periodontics', subjectNameAr: 'طب وجراحة اللثة (Periodontics)', subjectNameEn: 'Periodontics', groupCode: 'Group A1', clinicRoom: 'عيادة 1', quotaTargetCases: 8 },
  { id: 'alc-14', taId: 'user-ta-5', taName: 'د. خالد اليافعي', academicYear: '2025-2026', academicLevel: 'level4', semester: 'second', subjectId: 'periodontics', subjectNameAr: 'طب وجراحة اللثة (Periodontics)', subjectNameEn: 'Periodontics', groupCode: 'Group A2', clinicRoom: 'عيادة 2', quotaTargetCases: 8 },
  { id: 'alc-15', taId: 'user-ta-5', taName: 'د. خالد اليافعي', academicYear: '2025-2026', academicLevel: 'level4', semester: 'second', subjectId: 'periodontics', subjectNameAr: 'طب وجراحة اللثة (Periodontics)', subjectNameEn: 'Periodontics', groupCode: 'Group B1', clinicRoom: 'عيادة 3', quotaTargetCases: 8 },
  { id: 'alc-16', taId: 'user-ta-5', taName: 'د. خالد اليافعي', academicYear: '2025-2026', academicLevel: 'level4', semester: 'second', subjectId: 'periodontics', subjectNameAr: 'طب وجراحة اللثة (Periodontics)', subjectNameEn: 'Periodontics', groupCode: 'Group B2', clinicRoom: 'عيادة 4', quotaTargetCases: 8 },

  // Oral Surgery (4th Year Sem 2)
  { id: 'alc-17', taId: 'user-ta-6', taName: 'د. طارق باعباد', academicYear: '2025-2026', academicLevel: 'level4', semester: 'second', subjectId: 'oral_surgery', subjectNameAr: 'جراحة الفم والخلع (Oral Surgery)', subjectNameEn: 'Oral Surgery', groupCode: 'Group A1', clinicRoom: 'عيادة 1', quotaTargetCases: 10 },
  { id: 'alc-18', taId: 'user-ta-6', taName: 'د. طارق باعباد', academicYear: '2025-2026', academicLevel: 'level4', semester: 'second', subjectId: 'oral_surgery', subjectNameAr: 'جراحة الفم والخلع (Oral Surgery)', subjectNameEn: 'Oral Surgery', groupCode: 'Group A2', clinicRoom: 'عيادة 2', quotaTargetCases: 10 },

  // ===================== Level 5 - Semester 1 =====================
  // Operative (Level 5 Sem 1)
  { id: 'alc-19', taId: 'user-ta-1', taName: 'د. عمر باوزير', academicYear: '2025-2026', academicLevel: 'level5', semester: 'first', subjectId: 'operative', subjectNameAr: 'العلاج التحفظي المتقدم (Advanced Operative)', subjectNameEn: 'Operative Dentistry', groupCode: 'Group A1', clinicRoom: 'عيادة 1', quotaTargetCases: 11 },
  { id: 'alc-20', taId: 'user-ta-1', taName: 'د. عمر باوزير', academicYear: '2025-2026', academicLevel: 'level5', semester: 'first', subjectId: 'operative', subjectNameAr: 'العلاج التحفظي المتقدم (Advanced Operative)', subjectNameEn: 'Operative Dentistry', groupCode: 'Group A2', clinicRoom: 'عيادة 2', quotaTargetCases: 11 },
  { id: 'alc-21', taId: 'user-ta-4', taName: 'د. منى الكاف', academicYear: '2025-2026', academicLevel: 'level5', semester: 'first', subjectId: 'operative', subjectNameAr: 'العلاج التحفظي المتقدم (Advanced Operative)', subjectNameEn: 'Operative Dentistry', groupCode: 'Group B1', clinicRoom: 'عيادة 3', quotaTargetCases: 11 },
  { id: 'alc-22', taId: 'user-ta-4', taName: 'د. منى الكاف', academicYear: '2025-2026', academicLevel: 'level5', semester: 'first', subjectId: 'operative', subjectNameAr: 'العلاج التحفظي المتقدم (Advanced Operative)', subjectNameEn: 'Operative Dentistry', groupCode: 'Group B2', clinicRoom: 'عيادة 4', quotaTargetCases: 11 },

  // Endodontics (Level 5 Sem 1)
  { id: 'alc-23', taId: 'user-ta-2', taName: 'د. ياسمين النعمان', academicYear: '2025-2026', academicLevel: 'level5', semester: 'first', subjectId: 'endodontics', subjectNameAr: 'علاج الجذور المتقدم (Advanced Endodontics)', subjectNameEn: 'Endodontics', groupCode: 'Group A1', clinicRoom: 'عيادة 1', quotaTargetCases: 6 },
  { id: 'alc-24', taId: 'user-ta-2', taName: 'د. ياسمين النعمان', academicYear: '2025-2026', academicLevel: 'level5', semester: 'first', subjectId: 'endodontics', subjectNameAr: 'علاج الجذور المتقدم (Advanced Endodontics)', subjectNameEn: 'Endodontics', groupCode: 'Group A2', clinicRoom: 'عيادة 2', quotaTargetCases: 6 },
  { id: 'alc-25', taId: 'user-ta-2', taName: 'د. ياسمين النعمان', academicYear: '2025-2026', academicLevel: 'level5', semester: 'first', subjectId: 'endodontics', subjectNameAr: 'علاج الجذور المتقدم (Advanced Endodontics)', subjectNameEn: 'Endodontics', groupCode: 'Group B1', clinicRoom: 'عيادة 3', quotaTargetCases: 6 },

  // Fixed Prostho (Level 5 Sem 1)
  { id: 'alc-26', taId: 'user-ta-3', taName: 'د. فيصل السالم', academicYear: '2025-2026', academicLevel: 'level5', semester: 'first', subjectId: 'prosthodontics', subjectNameAr: 'الاستعاضة السنية الثابتة والمتحركة (Prostho)', subjectNameEn: 'Prosthodontics', groupCode: 'Group A1', clinicRoom: 'عيادة 1', quotaTargetCases: 8 },
  { id: 'alc-27', taId: 'user-ta-3', taName: 'د. فيصل السالم', academicYear: '2025-2026', academicLevel: 'level5', semester: 'first', subjectId: 'prosthodontics', subjectNameAr: 'الاستعاضة السنية الثابتة والمتحركة (Prostho)', subjectNameEn: 'Prosthodontics', groupCode: 'Group A2', clinicRoom: 'عيادة 2', quotaTargetCases: 8 },

  // Periodontics (Level 5 Sem 1)
  { id: 'alc-28', taId: 'user-ta-5', taName: 'د. خالد اليافعي', academicYear: '2025-2026', academicLevel: 'level5', semester: 'first', subjectId: 'periodontics', subjectNameAr: 'أمراض وجراحة اللثة (Periodontics)', subjectNameEn: 'Periodontics', groupCode: 'Group A1', clinicRoom: 'عيادة 1', quotaTargetCases: 9 },
  { id: 'alc-29', taId: 'user-ta-5', taName: 'د. خالد اليافعي', academicYear: '2025-2026', academicLevel: 'level5', semester: 'first', subjectId: 'periodontics', subjectNameAr: 'أمراض وجراحة اللثة (Periodontics)', subjectNameEn: 'Periodontics', groupCode: 'Group A2', clinicRoom: 'عيادة 2', quotaTargetCases: 9 },

  // Oral Surgery (Level 5 Sem 1)
  { id: 'alc-30', taId: 'user-ta-6', taName: 'د. طارق باعباد', academicYear: '2025-2026', academicLevel: 'level5', semester: 'first', subjectId: 'oral_surgery', subjectNameAr: 'جراحة الفم والوجه والفكين (Oral Surgery)', subjectNameEn: 'Oral & Maxillofacial Surgery', groupCode: 'Group A1', clinicRoom: 'عيادة 1', quotaTargetCases: 12 },
  { id: 'alc-31', taId: 'user-ta-6', taName: 'د. طارق باعباد', academicYear: '2025-2026', academicLevel: 'level5', semester: 'first', subjectId: 'oral_surgery', subjectNameAr: 'جراحة الفم والوجه والفكين (Oral Surgery)', subjectNameEn: 'Oral & Maxillofacial Surgery', groupCode: 'Group A2', clinicRoom: 'عيادة 2', quotaTargetCases: 12 },

  // Pediatric Dentistry (Level 5 Sem 1)
  { id: 'alc-32', taId: 'user-ta-4', taName: 'د. منى الكاف', academicYear: '2025-2026', academicLevel: 'level5', semester: 'first', subjectId: 'pedodontics', subjectNameAr: 'طب أسنان الأطفال (Pediatric Dentistry)', subjectNameEn: 'Pediatric Dentistry', groupCode: 'Group A1', clinicRoom: 'عيادة 1', quotaTargetCases: 6 },
  { id: 'alc-33', taId: 'user-ta-4', taName: 'د. منى الكاف', academicYear: '2025-2026', academicLevel: 'level5', semester: 'first', subjectId: 'pedodontics', subjectNameAr: 'طب أسنان الأطفال (Pediatric Dentistry)', subjectNameEn: 'Pediatric Dentistry', groupCode: 'Group A2', clinicRoom: 'عيادة 2', quotaTargetCases: 6 },
];

// Helper to look up the assigned TA for a student in a specific course
export function getAssignedTAForSubjectGroup(
  allocations: TeachingAssistantAllocation[],
  level: 'level4' | 'level5',
  semester: 'first' | 'second',
  subjectId: string,
  groupCode: string
): TeachingAssistantAllocation | undefined {
  return allocations.find(
    (a) =>
      a.academicLevel === level &&
      a.semester === semester &&
      a.subjectId === subjectId &&
      a.groupCode === groupCode
  );
}

// Helper to get all subject+group assignments for a TA
export function getTaAllocatedSubjectsAndGroups(
  allocations: TeachingAssistantAllocation[],
  taId: string
): TeachingAssistantAllocation[] {
  return allocations.filter((a) => a.taId === taId);
}

// Initial Seed Users for RBAC
export const SEED_USERS: UserAccount[] = [
  {
    id: 'user-founder',
    name: 'م. سهيل عبيدان (مؤسس المنظومة)',
    email: 'founder@clindent.edu',
    password: 'admin',
    role: 'founder',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    staffId: 'FND-001',
    isDemo: false,
    createdAt: '2026-01-01',
  },
  {
    id: 'user-dean',
    name: 'أ.د. عبد الرحمن المنصور (عميد الكلية)',
    email: 'dean@clindent.edu',
    password: '123',
    role: 'dean',
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=200&q=80',
    staffId: 'DEAN-2026',
    isDemo: false,
    createdAt: '2026-01-05',
  },
  {
    id: 'user-dept-head-1',
    name: 'د. طارق السعيد (رئيس قسم التحفظي)',
    email: 'head.operative@clindent.edu',
    password: '123',
    role: 'department_head',
    department: 'operative',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=200&q=80',
    staffId: 'HOD-OPT-101',
    isDemo: false,
    createdAt: '2026-01-10',
  },
  {
    id: 'user-dept-head-endo',
    name: 'د. إبراهيم الخالدي (رئيس قسم علاج الجذور)',
    email: 'head.endo@clindent.edu',
    password: '123',
    role: 'department_head',
    department: 'endodontics',
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=200&q=80',
    staffId: 'HOD-ENDO-102',
    isDemo: false,
    createdAt: '2026-01-10',
  },
  {
    id: 'user-dept-head-surg',
    name: 'د. منصور الغامدي (رئيس قسم جراحة الفم)',
    email: 'head.surgery@clindent.edu',
    password: '123',
    role: 'department_head',
    department: 'oral_surgery',
    avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=200&q=80',
    staffId: 'HOD-SURG-103',
    isDemo: false,
    createdAt: '2026-01-10',
  },
  {
    id: 'user-dept-head-prosth',
    name: 'د. عبد العزيز الفضلي (رئيس قسم التركيبات)',
    email: 'head.prosth@clindent.edu',
    password: '123',
    role: 'department_head',
    department: 'prosthodontics',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80',
    staffId: 'HOD-PROS-104',
    isDemo: false,
    createdAt: '2026-01-10',
  },
  {
    id: 'user-dept-head-perio',
    name: 'د. وائل باحارث (رئيس قسم علاج اللثة)',
    email: 'head.perio@clindent.edu',
    password: '123',
    role: 'department_head',
    department: 'periodontics',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    staffId: 'HOD-PERI-105',
    isDemo: false,
    createdAt: '2026-01-10',
  },
  {
    id: 'user-dept-head-pedo',
    name: 'د. هدى الدوسري (رئيسة قسم طب أسنان الأطفال)',
    email: 'head.pedo@clindent.edu',
    password: '123',
    role: 'department_head',
    department: 'pedodontics',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    staffId: 'HOD-PEDO-106',
    isDemo: false,
    createdAt: '2026-01-10',
  },
  {
    id: 'user-dept-head-ortho',
    name: 'د. نورة السبيعي (رئيسة قسم تقويم الأسنان)',
    email: 'head.ortho@clindent.edu',
    password: '123',
    role: 'department_head',
    department: 'orthodontics',
    avatar: 'https://images.unsplash.com/photo-1594824813597-392942468305?auto=format&fit=crop&w=200&q=80',
    staffId: 'HOD-ORTH-107',
    isDemo: false,
    createdAt: '2026-01-10',
  },
  {
    id: 'user-supervisor-1',
    name: 'د. سارة الشمري (مشرفة إكلينيكية)',
    email: 'supervisor.sarah@clindent.edu',
    password: '123',
    role: 'supervisor',
    department: 'endodontics',
    clinicalGroup: 'Group A1',
    avatar: 'https://images.unsplash.com/photo-1594824813597-392942468305?auto=format&fit=crop&w=200&q=80',
    staffId: 'SUP-END-202',
    isDemo: false,
    createdAt: '2026-01-15',
  },
  {
    id: 'user-supervisor-2',
    name: 'د. فهد القحطاني (مشرف جراحة الفم)',
    email: 'supervisor.fahad@clindent.edu',
    password: '123',
    role: 'supervisor',
    department: 'oral_surgery',
    clinicalGroup: 'Group A2',
    avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=200&q=80',
    staffId: 'SUP-SURG-305',
    isDemo: false,
    createdAt: '2026-01-15',
  },
  // Teaching Assistants
  {
    id: 'user-ta-1',
    name: 'د. عمر باوزير (معيد إكلينيكي)',
    email: 'ta.omar@clindent.edu',
    password: '123',
    role: 'teaching_assistant',
    department: 'operative',
    assignedSubject: 'operative',
    clinicalGroup: 'Group A1',
    assignedGroupName: 'Group A1',
    assignedStudentIds: ['user-student-1', 'user-student-2', 'user-student-5'],
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=200&q=80',
    staffId: 'TA-OPT-401',
    isDemo: false,
    createdAt: '2026-01-20',
  },
  {
    id: 'user-ta-2',
    name: 'د. ياسمين النعمان (معيدة إكلينيكية)',
    email: 'ta.yasmin@clindent.edu',
    password: '123',
    role: 'teaching_assistant',
    department: 'endodontics',
    assignedSubject: 'endodontics',
    clinicalGroup: 'Group A1',
    assignedGroupName: 'Group A1',
    assignedStudentIds: ['user-student-1', 'user-student-2', 'user-student-4'],
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=200&q=80',
    staffId: 'TA-END-402',
    isDemo: false,
    createdAt: '2026-01-20',
  },
  {
    id: 'user-ta-3',
    name: 'د. فيصل السالم (معيد إكلينيكي)',
    email: 'ta.faisal@clindent.edu',
    password: '123',
    role: 'teaching_assistant',
    department: 'prosthodontics',
    assignedSubject: 'prosthodontics',
    clinicalGroup: 'Group A1',
    assignedGroupName: 'Group A1',
    assignedStudentIds: ['user-student-1', 'user-student-6'],
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80',
    staffId: 'TA-PROSTH-403',
    isDemo: false,
    createdAt: '2026-01-20',
  },
  {
    id: 'user-ta-4',
    name: 'د. منى الكاف (معيدة إكلينيكية)',
    email: 'ta.mona@clindent.edu',
    password: '123',
    role: 'teaching_assistant',
    department: 'pedodontics',
    assignedSubject: 'pedodontics',
    clinicalGroup: 'Group A1',
    assignedGroupName: 'Group A1',
    assignedStudentIds: ['user-student-1', 'user-student-2'],
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    staffId: 'TA-PEDO-404',
    isDemo: false,
    createdAt: '2026-01-20',
  },
  {
    id: 'user-ta-5',
    name: 'د. خالد اليافعي (معيد إكلينيكي)',
    email: 'ta.khaled@clindent.edu',
    password: '123',
    role: 'teaching_assistant',
    department: 'periodontics',
    assignedSubject: 'periodontics',
    clinicalGroup: 'Group A1',
    assignedGroupName: 'Group A1',
    assignedStudentIds: ['user-student-1', 'user-student-2'],
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    staffId: 'TA-PERIO-405',
    isDemo: false,
    createdAt: '2026-01-20',
  },
  {
    id: 'user-ta-6',
    name: 'د. طارق باعباد (معيد إكلينيكي)',
    email: 'ta.tareq@clindent.edu',
    password: '123',
    role: 'teaching_assistant',
    department: 'oral_surgery',
    assignedSubject: 'oral_surgery',
    clinicalGroup: 'Group A1',
    assignedGroupName: 'Group A1',
    assignedStudentIds: ['user-student-1', 'user-student-2'],
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80',
    staffId: 'TA-SURG-406',
    isDemo: false,
    createdAt: '2026-01-20',
  },
  // Students
  {
    id: 'user-student-1',
    name: 'أحمد بن خالد العتيبي',
    email: 'student.ahmed@clindent.edu',
    password: '123',
    role: 'student',
    studentId: 'DEN-2022-441',
    academicYear: '2025-2026',
    academicLevel: 'level5',
    semester: 'first',
    clinicalGroup: 'Group A1',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    isDemo: false,
    createdAt: '2026-02-01',
  },
  {
    id: 'user-student-2',
    name: 'ريما بنت ناصر الهذلي',
    email: 'student.reema@clindent.edu',
    password: '123',
    role: 'student',
    studentId: 'DEN-2022-512',
    academicYear: '2025-2026',
    academicLevel: 'level5',
    semester: 'first',
    clinicalGroup: 'Group A1',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    isDemo: false,
    createdAt: '2026-02-01',
  },
  {
    id: 'user-student-3',
    name: 'يوسف بدر الحربي',
    email: 'student.yousef@clindent.edu',
    password: '123',
    role: 'student',
    studentId: 'DEN-2022-389',
    academicYear: '2025-2026',
    academicLevel: 'level4',
    semester: 'first',
    clinicalGroup: 'Group A2',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    isDemo: false,
    createdAt: '2026-02-01',
  },
  {
    id: 'user-student-4',
    name: 'سارة عبد الرحمن الدوسري',
    email: 'student.sarah@clindent.edu',
    password: '123',
    role: 'student',
    studentId: 'DEN-2022-498',
    academicYear: '2025-2026',
    academicLevel: 'level5',
    semester: 'first',
    clinicalGroup: 'Group A2',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    isDemo: false,
    createdAt: '2026-02-01',
  },
  {
    id: 'user-student-5',
    name: 'طارق عبد الله الشهري',
    email: 'student.tariq@clindent.edu',
    password: '123',
    role: 'student',
    studentId: 'DEN-2022-320',
    academicYear: '2025-2026',
    academicLevel: 'level4',
    semester: 'first',
    clinicalGroup: 'Group A1',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80',
    isDemo: false,
    createdAt: '2026-02-01',
  },
  {
    id: 'user-student-6',
    name: 'هدى سعيد المنصور',
    email: 'student.huda@clindent.edu',
    password: '123',
    role: 'student',
    studentId: 'DEN-2022-355',
    academicYear: '2025-2026',
    academicLevel: 'level4',
    semester: 'first',
    clinicalGroup: 'Group B1',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    isDemo: false,
    createdAt: '2026-02-01',
  },
];

// Initial Seed Clinical Cases
export const SEED_CASES: ClinicalCase[] = [
  {
    id: 'case-101',
    caseNumber: 'CLIN-2026-0891',
    title: 'معالجة لبية كاملة للرحى السفلية اليمنى 46 مع حشوة وتد وتاج',
    department: 'endodontics',
    studentId: 'user-student-1',
    studentName: 'أحمد بن خالد العتيبي',
    studentAcademicYear: 'السنة الخامسة (امتياز / إكلينيكي)',
    academicLevel: 'level5',
    semester: 'first',
    clinicalGroup: 'Group A1',
    supervisorId: 'user-supervisor-1',
    supervisorName: 'د. سارة الشمري',
    assignedTaId: 'user-ta-2',
    assignedTaName: 'د. ياسمين النعمان',
    dentitionType: 'permanent',
    patient: {
      name: 'عبد الله صالح الغامدي',
      fileNumber: 'P-94821',
      nationalId: '1092837461',
      age: 34,
      gender: 'male',
      phone: '+966 50 123 4567',
      medicalHistory: ['سليم، لا يوجد أمراض مزمنة', 'لا يوجد تحسس دوائي'],
      chiefComplaint: 'ألم حاد متواصل ومفاجئ في الجهة السفلية اليمنى يزداد مع المشروبات الباردة والساخنة.',
      vitalSigns: {
        bloodPressure: '120/80 mmHg',
        pulse: '74 bpm',
        bloodSugar: '95 mg/dL',
      },
    },
    diagnosis: 'التهاب لب حاد غير ردود (Symptomatic Irreversible Pulpitis) مع التهاب نسج حول ذروية أعراضي للسن 46.',
    treatmentPlan: '1. تخدير موضعي وعزل بحاجز مطاطي (Rubber Dam)\n2. فتح حجرة اللب وتحديد 3 قنوات (MB, ML, D)\n3. تشكيل وتطهير القنوات بنظام Rotary Files وتطهير بـ NaOCl 2.5%\n4. حشو القنوات بـ Gutta-Percha وحشوة لبية متقدمة.',
    procedureSteps: [
      { id: 'st-1', stepNumber: 1, title: 'التخدير الموضعي والعزل بالحاجز المطاطي', description: 'Inferior Alveolar Nerve Block + Rubber Dam isolation #14 Clamp', isCompleted: true, supervisorSigned: true, supervisorName: 'د. ياسمين النعمان', timestamp: '2026-08-20 09:30' },
      { id: 'st-2', stepNumber: 2, title: 'الوصول اللبي وتحديد الطول العامل', description: 'Access Cavity prep & Electronic Apex Locator + Working Length X-ray (MB: 21mm, ML: 21mm, D: 21.5mm)', isCompleted: true, supervisorSigned: true, supervisorName: 'د. ياسمين النعمان', timestamp: '2026-08-20 10:15' },
      { id: 'st-3', stepNumber: 3, title: 'التحضير الآلي والإرواء الدوائي', description: 'NiTi Rotary instrumentation up to F2 with copious 2.5% NaOCl and 17% EDTA irrigation', isCompleted: true, supervisorSigned: true, supervisorName: 'د. ياسمين النعمان', timestamp: '2026-08-20 11:00' },
      { id: 'st-4', stepNumber: 4, title: 'حشو الأقنية السنية (Obturation)', description: 'Single cone + Bioceramic Sealer with master cone radiograph confirmation', isCompleted: true, supervisorSigned: true, supervisorName: 'د. ياسمين النعمان', timestamp: '2026-08-20 11:45' },
    ],
    dentalChart: {
      '46': {
        condition: 'endo_rct',
        surfaces: { occlusal: true, mesial: true, distal: false, buccal: true, lingual: false },
        notes: 'تم إنهاء معالجة العصب بنجاح بدون مضاعفات سريرية.',
        mobility: '0',
        pocketDepthMm: 2,
      },
      '47': {
        condition: 'sound',
        surfaces: {},
      },
      '45': {
        condition: 'filling_composite',
        surfaces: { occlusal: true },
      },
    },
    radiographs: [SAMPLE_RADIOGRAPHS[1], SAMPLE_RADIOGRAPHS[0]],
    clinicalPhotos: [],
    status: 'approved',
    quotaUnits: 1,
    evaluation: {
      grade: 96,
      criteria: {
        infectionControl: 20,
        anesthesiaCavityPrep: 24,
        restorationObturation: 24,
        patientManagement: 14,
        professionalEthics: 14,
      },
      feedbackNotes: 'عمل سريري متميز ودقيق جداً. العزل بالحاجز المطاطي كان محكماً، وتكثيف المادة الحاشية ممتاز ووصل للذروة التشريحية بشكل مثالي. أحسنت!',
      evaluatedAt: '2026-08-20 12:30',
      supervisorId: 'user-ta-2',
      supervisorName: 'د. ياسمين النعمان',
      supervisorSignature: 'Dr. Yasmin Al-Noaman, Teaching Assistant',
    },
    createdAt: '2026-08-20 09:00',
    updatedAt: '2026-08-20 12:30',
  },
  {
    id: 'case-102',
    caseNumber: 'CLIN-2026-0892',
    title: 'حشوة كمبوزيت تجميلية Class II للرحى العلوية 16 مع عزل مطاطي',
    department: 'operative',
    studentId: 'user-student-1',
    studentName: 'أحمد بن خالد العتيبي',
    studentAcademicYear: 'السنة الخامسة (امتياز / إكلينيكي)',
    academicLevel: 'level5',
    semester: 'first',
    clinicalGroup: 'Group A1',
    supervisorId: 'user-supervisor-1',
    supervisorName: 'د. سارة الشمري',
    assignedTaId: 'user-ta-1',
    assignedTaName: 'د. عمر باوزير',
    dentitionType: 'permanent',
    patient: {
      name: 'منى إبراهيم الدوسري',
      fileNumber: 'P-98112',
      nationalId: '1088761234',
      age: 26,
      gender: 'female',
      phone: '+966 55 987 6543',
      medicalHistory: ['حساسية من البنسلين'],
      allergies: 'Penicillin allergy',
      chiefComplaint: 'انحشار الطعام بين الأضراس العلوية في الجانب الأيمن مع حساسية خفيفة للحلويات.',
      vitalSigns: {
        bloodPressure: '115/75 mmHg',
        pulse: '68 bpm',
      },
    },
    diagnosis: 'تسوس ملاصق إنسي طاحن Class II MO Caries في السن 16.',
    treatmentPlan: 'حفر وتجريف التسوس مع الحفاظ على النسيج السني وتطبيق نظام ربط سنّي من الجيل السابع وحشوة نانو-كمبوزيت.',
    procedureSteps: [
      { id: 'st-21', stepNumber: 1, title: 'عزل وحفر التجويف السني', description: 'Cavity preparation with rounded internal line angles & caries removal', isCompleted: true, supervisorSigned: true, supervisorName: 'د. عمر باوزير', timestamp: '2026-08-26 10:00' },
      { id: 'st-22', stepNumber: 2, title: 'تركيب المصفوفة الملاصقة وحشوة الكمبوزيت', description: 'Sectional matrix ring + universal adhesive + nanohybrid composite layering', isCompleted: true, supervisorSigned: false, timestamp: '2026-08-26 10:45' },
    ],
    dentalChart: {
      '16': {
        condition: 'filling_composite',
        surfaces: { occlusal: true, mesial: true },
        notes: 'حشوة كمبوزيت جمالية Class II MO.',
      },
      '15': {
        condition: 'sound',
        surfaces: {},
      },
    },
    radiographs: [SAMPLE_RADIOGRAPHS[2]],
    clinicalPhotos: [],
    status: 'under_review',
    quotaUnits: 1,
    createdAt: '2026-08-26 09:30',
    updatedAt: '2026-08-26 11:15',
  },
  {
    id: 'case-103',
    caseNumber: 'CLIN-2026-0893',
    title: 'خلع جراحي لضرس العقل المنطمر جزئياً 38 مع تجريف وخياطة',
    department: 'oral_surgery',
    studentId: 'user-student-2',
    studentName: 'ريما بنت ناصر الهذلي',
    studentAcademicYear: 'السنة الخامسة (امتياز / إكلينيكي)',
    academicLevel: 'level5',
    semester: 'first',
    clinicalGroup: 'Group A1',
    supervisorId: 'user-supervisor-2',
    supervisorName: 'د. فهد القحطاني',
    assignedTaId: 'user-ta-6',
    assignedTaName: 'د. طارق باعباد',
    dentitionType: 'permanent',
    patient: {
      name: 'خالد عبد العزيز الشريف',
      fileNumber: 'P-91043',
      nationalId: '1076543219',
      age: 22,
      gender: 'male',
      phone: '+966 54 321 0987',
      medicalHistory: ['سليم تماماً'],
      chiefComplaint: 'ألم وتورم متكرر في زاوية الفك السفلي الأيسر مع صعوبة في فتح الفم (Pericoronitis).',
      vitalSigns: {
        bloodPressure: '125/82 mmHg',
        pulse: '78 bpm',
      },
    },
    diagnosis: 'Mesioangular Partially Impacted 3rd Molar #38 with recurrent pericoronitis.',
    treatmentPlan: 'خلع جراحي مع رفع شريحة مخاطية سمحاقية وقص عظمي وتجزيء التاج وخياطة متفرقة.',
    procedureSteps: [
      { id: 'st-31', stepNumber: 1, title: 'التخدير الموضعي ورفع الشريحة', description: 'IANB block + Triangular mucoperiosteal flap reflection', isCompleted: true, supervisorSigned: true, supervisorName: 'د. طارق باعباد' },
      { id: 'st-32', stepNumber: 2, title: 'الخلع السريري والخياطة', description: 'Bone guttering, crown sectioning, complete luxation, socket curettage & 3-0 Silk sutures', isCompleted: true, supervisorSigned: true, supervisorName: 'د. طارق باعباد' },
    ],
    dentalChart: {
      '38': {
        condition: 'extraction',
        surfaces: {},
        notes: 'تم الخلع الجراحي بالكامل مع خياطة 3 غرز متفرقة.',
      },
    },
    radiographs: [SAMPLE_RADIOGRAPHS[0]],
    clinicalPhotos: [],
    status: 'needs_correction',
    quotaUnits: 1,
    evaluation: {
      grade: 72,
      criteria: {
        infectionControl: 18,
        anesthesiaCavityPrep: 18,
        restorationObturation: 16,
        patientManagement: 10,
        professionalEthics: 10,
      },
      feedbackNotes: 'خطوات الجراحة جيدة، لكن يرجى إضافة تفاصيل ونوع الخيوط الجراحية المستخدمة وموعد فك الغرز في خطة المتابعة وإرفاق أشعة التأكيد بعد الخلع (Post-Op X-ray).',
      revisionRequests: [
        'إرفاق صورة أشعة التأكيد بعد الجراحة (Post-Op radiograph)',
        'تحديد موعد إزالة الغرز الجراحية وتعليمات ما بعد الخلع في ملف المريض',
      ],
      evaluatedAt: '2026-08-25 14:00',
      supervisorId: 'user-ta-6',
      supervisorName: 'د. طارق باعباد',
      supervisorSignature: 'Dr. Tareq Ba-Abbad, TA Oral Surgery',
    },
    createdAt: '2026-08-25 11:00',
    updatedAt: '2026-08-25 14:00',
  },
  {
    id: 'case-104',
    caseNumber: 'CLIN-2026-0894',
    title: 'تقليح وتجريف فوق وتحت اللثة وتنظيف جير شامل لمريض مصاب بالتهاب لثة',
    department: 'periodontics',
    studentId: 'user-student-2',
    studentName: 'ريما بنت ناصر الهذلي',
    studentAcademicYear: 'السنة الخامسة (امتياز / إكلينيكي)',
    academicLevel: 'level5',
    semester: 'first',
    clinicalGroup: 'Group A1',
    supervisorId: 'user-supervisor-1',
    supervisorName: 'د. سارة الشمري',
    assignedTaId: 'user-ta-5',
    assignedTaName: 'د. خالد اليافعي',
    dentitionType: 'permanent',
    patient: {
      name: 'فاطمة محمد العمري',
      fileNumber: 'P-88712',
      nationalId: '1065432198',
      age: 42,
      gender: 'female',
      phone: '+966 56 789 0123',
      medicalHistory: ['سكري نوع 2 منضبط (HbA1c 6.8%)'],
      chiefComplaint: 'نزف لثوي مستمر عند تنظيف الأسنان بالفرشاة مع رائحة فم غير مستحبة.',
      vitalSigns: {
        bloodPressure: '128/84 mmHg',
        bloodSugar: '110 mg/dL',
      },
    },
    diagnosis: 'Generalized Stage II Grade B Periodontitis with 4-5mm pocketing.',
    treatmentPlan: 'جلسة تقليح وتجريف لكافة الأرباع الفموية بجهاز Ultrasonic Scaler مع كحاتات Gracey Curettes وتطبيق معجون فلورايد.',
    procedureSteps: [
      { id: 'st-41', stepNumber: 1, title: 'الفحص اللثوي ومخطط الجيوب (Perio Charting)', description: 'Probing depth measurement, Bleeding on probing (BOP 65%) recorded', isCompleted: true, supervisorSigned: true, supervisorName: 'د. خالد اليافعي' },
      { id: 'st-42', stepNumber: 2, title: 'التقليح والتلميع وإرشادات العناية الفموية', description: 'Full mouth scaling, root planning, air polishing and OHI instructions', isCompleted: true, supervisorSigned: true, supervisorName: 'د. خالد اليافعي' },
    ],
    dentalChart: {
      '31': { condition: 'sound', surfaces: {}, pocketDepthMm: 4, mobility: 'I' },
      '41': { condition: 'sound', surfaces: {}, pocketDepthMm: 4, mobility: 'I' },
      '32': { condition: 'sound', surfaces: {}, pocketDepthMm: 4 },
      '42': { condition: 'sound', surfaces: {}, pocketDepthMm: 4 },
    },
    radiographs: [SAMPLE_RADIOGRAPHS[0]],
    clinicalPhotos: [],
    status: 'approved',
    quotaUnits: 1,
    evaluation: {
      grade: 92,
      criteria: {
        infectionControl: 20,
        anesthesiaCavityPrep: 22,
        restorationObturation: 23,
        patientManagement: 14,
        professionalEthics: 13,
      },
      feedbackNotes: 'تعامل ممتاز مع المريضة وتقديم تعليمات العناية الفموية بشكل احترافي. تم إزالة الرواسب الجيرية تحت اللثوية بكفاءة عالية.',
      evaluatedAt: '2026-08-27 15:30',
      supervisorId: 'user-ta-5',
      supervisorName: 'د. خالد اليافعي',
    },
    createdAt: '2026-08-27 13:00',
    updatedAt: '2026-08-27 15:30',
  },
  {
    id: 'case-105',
    caseNumber: 'CLIN-2026-0895',
    title: 'تاج زيركونيا خزفي للسن 21 الأمامي بعد معالجة لبية مع طبعة سيليكونية',
    department: 'prosthodontics',
    studentId: 'user-student-3',
    studentName: 'يوسف بدر الحربي',
    studentAcademicYear: 'السنة الرابعة (سريري)',
    academicLevel: 'level4',
    semester: 'first',
    clinicalGroup: 'Group A2',
    supervisorId: 'user-supervisor-1',
    supervisorName: 'د. سارة الشمري',
    assignedTaId: 'user-ta-3',
    assignedTaName: 'د. فيصل السالم',
    dentitionType: 'permanent',
    patient: {
      name: 'ماجد سالم القرني',
      fileNumber: 'P-77401',
      nationalId: '1054321987',
      age: 28,
      gender: 'male',
      phone: '+966 50 555 1234',
      medicalHistory: ['سليم'],
      chiefComplaint: 'تغير لون السن الأمامي ورغبة في تحسين المظهر الجمالي والابتسامة.',
      vitalSigns: { bloodPressure: '120/78 mmHg' },
    },
    diagnosis: 'Discolored endodontically treated Maxillary Left Central Incisor #21.',
    treatmentPlan: 'تحضير السن لتاج زيركون كامل مع خط إنهاء Chamfer وطبعة مادية Addition Silicone وتثبيت تاج مؤقت.',
    procedureSteps: [
      { id: 'st-51', stepNumber: 1, title: 'تحضير السن السريري', description: 'Crown prep with 1.2mm axial reduction and clear finish line', isCompleted: false },
    ],
    dentalChart: {
      '21': {
        condition: 'crown',
        surfaces: { occlusal: true, buccal: true, lingual: true, mesial: true, distal: true },
        notes: 'تحضير تاج زيركون تجميلي.',
      },
    },
    radiographs: [SAMPLE_RADIOGRAPHS[0]],
    clinicalPhotos: [],
    status: 'draft',
    quotaUnits: 1,
    createdAt: '2026-08-30 10:00',
    updatedAt: '2026-08-30 10:00',
  },
  {
    id: 'case-106',
    caseNumber: 'CLIN-2026-0896',
    title: 'حشوة كمبوزيت فئة ثانية Class II DO للضرس 36 مع عزل كامل',
    department: 'operative',
    studentId: 'user-student-5',
    studentName: 'طارق عبد الله الشهري',
    studentAcademicYear: 'السنة الرابعة (سريري)',
    academicLevel: 'level4',
    semester: 'first',
    clinicalGroup: 'Group A1',
    supervisorId: 'user-supervisor-1',
    supervisorName: 'د. سارة الشمري',
    assignedTaId: 'user-ta-1',
    assignedTaName: 'د. عمر باوزير',
    dentitionType: 'permanent',
    patient: {
      name: 'سالم أحمد الشهري',
      fileNumber: 'P-99214',
      nationalId: '1098437210',
      age: 24,
      gender: 'male',
      phone: '+966 50 111 2233',
      medicalHistory: ['سليم، لا يوجد أمراض مزمنة'],
      chiefComplaint: 'حساسية مع السكريات وألم خفيف عند المضغ.',
      vitalSigns: { bloodPressure: '118/76 mmHg', pulse: '72 bpm' },
    },
    diagnosis: 'تسوس عميق طاحن وحشي في الضرس السفلي الأيسر 36.',
    treatmentPlan: 'تجريف التسوس بحذر، عزل بحاجز مطاطي، تطبيق بطانة بيوكيميائية، ووضع حشوة كمبوزيت نانوية.',
    procedureSteps: [
      { id: 'st-61', stepNumber: 1, title: 'التخدير الموضعي والعزل بالحاجز المطاطي', description: 'Mandibular block + Rubber dam isolation on tooth 36', isCompleted: true, supervisorSigned: true, signedByName: 'د. عمر باوزير', signedByRole: 'teaching_assistant', signedTimestamp: '2026-08-28 09:30' },
      { id: 'st-62', stepNumber: 2, title: 'تجريف التسوس وتحضير التجويف', description: 'Caries excavation, pulp protection liner Dycal placement', isCompleted: true, supervisorSigned: true, signedByName: 'د. عمر باوزير', signedByRole: 'teaching_assistant', signedTimestamp: '2026-08-28 10:15' },
      { id: 'st-63', stepNumber: 3, title: 'وضع حشوة الكمبوزيت والإنهاء والتلميع', description: 'Sectional matrix ring, etch & bond, layering nano-composite & occlusal adjustment', isCompleted: true, supervisorSigned: true, signedByName: 'د. عمر باوزير', signedByRole: 'teaching_assistant', signedTimestamp: '2026-08-28 11:00' },
    ],
    dentalChart: {
      '36': { condition: 'filling_composite', surfaces: { occlusal: true, distal: true }, notes: 'حشوة كمبوزيت ممتازة Class II DO.' },
    },
    radiographs: [SAMPLE_RADIOGRAPHS[2]],
    clinicalPhotos: [],
    status: 'approved',
    quotaUnits: 1,
    evaluation: {
      grade: 94,
      criteria: {
        infectionControl: 20,
        anesthesiaCavityPrep: 24,
        restorationObturation: 23,
        patientManagement: 14,
        professionalEthics: 13,
      },
      feedbackNotes: 'عمل سريري متقن للغاية من الطالب طارق. التحضير كان نظيفاً وحواف الحشوة مسقولة جيداً.',
      evaluatedAt: '2026-08-28 11:30',
      supervisorId: 'user-ta-1',
      supervisorName: 'د. عمر باوزير',
    },
    createdAt: '2026-08-28 09:00',
    updatedAt: '2026-08-28 11:30',
  },
  {
    id: 'case-107',
    caseNumber: 'CLIN-2026-0897',
    title: 'معالجة لبية كاملة للقناة الواحدة للثنية العلوية اليمنى 11 بعد رض سني',
    department: 'endodontics',
    studentId: 'user-student-4',
    studentName: 'سارة عبد الرحمن الدوسري',
    studentAcademicYear: 'السنة الخامسة (امتياز / إكلينيكي)',
    academicLevel: 'level5',
    semester: 'first',
    clinicalGroup: 'Group A2',
    supervisorId: 'user-supervisor-1',
    supervisorName: 'د. سارة الشمري',
    assignedTaId: 'user-ta-2',
    assignedTaName: 'د. ياسمين النعمان',
    dentitionType: 'permanent',
    patient: {
      name: 'نورة عبد الله المطيري',
      fileNumber: 'P-98331',
      nationalId: '1087654329',
      age: 21,
      gender: 'female',
      phone: '+966 53 444 5566',
      medicalHistory: ['لا يوجد أمراض مزمنة'],
      chiefComplaint: 'تغير لون السن الأمامي مع ألم عند الطرق بعد تعرض لحادث سابق.',
      vitalSigns: { bloodPressure: '112/70 mmHg', pulse: '70 bpm' },
    },
    diagnosis: 'تموت لب السن 11 (Pulp Necrosis) مع التهاب ذروي مزمن (Asymptomatic Apical Periodontitis).',
    treatmentPlan: 'معالجة لبية كاملة بالقناة الواحدة وتكثيف حراري جانبي وإغلاق مؤقت تمهيداً لحشوة تجميلية.',
    procedureSteps: [
      { id: 'st-71', stepNumber: 1, title: 'العزل بالرابردام والوصول اللبي', description: 'Lingual access cavity & Rubber Dam #9 Clamp', isCompleted: true, supervisorSigned: true, signedByName: 'د. ياسمين النعمان', signedByRole: 'teaching_assistant', signedTimestamp: '2026-08-29 10:00' },
      { id: 'st-72', stepNumber: 2, title: 'تحديد الطول وإعداد القناة', description: 'Working length 22.5mm, Protaper Gold F3 prep with NaOCl 3%', isCompleted: true, supervisorSigned: true, signedByName: 'د. ياسمين النعمان', signedByRole: 'teaching_assistant', signedTimestamp: '2026-08-29 10:45' },
      { id: 'st-73', stepNumber: 3, title: 'حشو القناة السنية (Obturation)', description: 'Bioceramic single cone with warm vertical condensation & master cone radiograph', isCompleted: true, supervisorSigned: true, signedByName: 'د. ياسمين النعمان', signedByRole: 'teaching_assistant', signedTimestamp: '2026-08-29 11:30' },
    ],
    dentalChart: {
      '11': { condition: 'endo_rct', surfaces: { lingual: true }, notes: 'معالجة لبية ممتازة للسن 11.' },
    },
    radiographs: [SAMPLE_RADIOGRAPHS[1]],
    clinicalPhotos: [],
    status: 'under_review',
    quotaUnits: 1,
    createdAt: '2026-08-29 09:45',
    updatedAt: '2026-08-29 11:30',
  },
  {
    id: 'case-108',
    caseNumber: 'CLIN-2026-0898',
    title: 'طبعة أولية وثانوية لطقم أسنان جزئي متحرك للفك السفلي Kennedy Class I',
    department: 'prosthodontics',
    studentId: 'user-student-6',
    studentName: 'هدى سعيد المنصور',
    studentAcademicYear: 'السنة الرابعة (سريري)',
    academicLevel: 'level4',
    semester: 'first',
    clinicalGroup: 'Group B1',
    supervisorId: 'user-supervisor-1',
    supervisorName: 'د. سارة الشمري',
    assignedTaId: 'user-ta-3',
    assignedTaName: 'د. فيصل السالم',
    dentitionType: 'permanent',
    patient: {
      name: 'إبراهيم ناصر القحطاني',
      fileNumber: 'P-94302',
      nationalId: '1043219876',
      age: 58,
      gender: 'male',
      phone: '+966 50 777 8899',
      medicalHistory: ['ضغط دم مسيطر عليه بدواء'],
      chiefComplaint: 'فقدان الأضراس الخلفية في الفك السفلي وصعوبة في مضغ الطعام.',
      vitalSigns: { bloodPressure: '130/85 mmHg', pulse: '76 bpm' },
    },
    diagnosis: 'Mandibular Kennedy Class I partially edentulous arch.',
    treatmentPlan: 'تصميم طقم جزئي معدني Co-Cr مع مساند إطباقية وخطافات ضامة وطبعة وظيفية دقيقة.',
    procedureSteps: [
      { id: 'st-81', stepNumber: 1, title: 'تحضير الأسنان الداعمة ومساند الإطباق (Rest Seats)', description: 'Occlusal rest seat preparation on #34, #44 with guide planes', isCompleted: true, supervisorSigned: true, signedByName: 'د. فيصل السالم', signedByRole: 'teaching_assistant', signedTimestamp: '2026-08-30 09:30' },
      { id: 'st-82', stepNumber: 2, title: 'أخذ الطبعة الوظيفية النهائية بصينية مخصصة', description: 'Custom tray border molding with green stick & light body addition silicone impression', isCompleted: true, supervisorSigned: true, signedByName: 'د. فيصل السالم', signedByRole: 'teaching_assistant', signedTimestamp: '2026-08-30 10:30' },
    ],
    dentalChart: {
      '35': { condition: 'missing', surfaces: {} },
      '36': { condition: 'missing', surfaces: {} },
      '37': { condition: 'missing', surfaces: {} },
      '45': { condition: 'missing', surfaces: {} },
      '46': { condition: 'missing', surfaces: {} },
      '47': { condition: 'missing', surfaces: {} },
    },
    radiographs: [SAMPLE_RADIOGRAPHS[0]],
    clinicalPhotos: [],
    status: 'approved',
    quotaUnits: 1,
    evaluation: {
      grade: 90,
      criteria: {
        infectionControl: 20,
        anesthesiaCavityPrep: 22,
        restorationObturation: 22,
        patientManagement: 13,
        professionalEthics: 13,
      },
      feedbackNotes: 'طبعة ممتازة المعالم والحدود التشريحية واضحة.',
      evaluatedAt: '2026-08-30 11:00',
      supervisorId: 'user-ta-3',
      supervisorName: 'د. فيصل السالم',
    },
    createdAt: '2026-08-30 09:00',
    updatedAt: '2026-08-30 11:00',
  },
];

// Initial Audit Trail Logs
export const SEED_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    timestamp: '2026-08-20 09:00:12',
    actorId: 'user-student-1',
    actorName: 'أحمد بن خالد العتيبي',
    actorRole: 'student',
    action: 'CREATE_CASE',
    entityType: 'case',
    entityId: 'case-101',
    details: 'إنشاء حالة سريرية جديدة: معالجة لبية كاملة للرحى 46',
  },
  {
    id: 'log-2',
    timestamp: '2026-08-20 11:55:00',
    actorId: 'user-student-1',
    actorName: 'أحمد بن خالد العتيبي',
    actorRole: 'student',
    action: 'SUBMIT_CASE_FOR_REVIEW',
    entityType: 'case',
    entityId: 'case-101',
    details: 'إرسال الحالة CLIN-2026-0891 للمشرفة د. سارة الشمري للاعتماد الإكلينيكي',
  },
  {
    id: 'log-3',
    timestamp: '2026-08-20 12:30:45',
    actorId: 'user-supervisor-1',
    actorName: 'د. سارة الشمري',
    actorRole: 'supervisor',
    action: 'APPROVE_CASE',
    entityType: 'case',
    entityId: 'case-101',
    details: 'اعتماد الحالة السريرية CLIN-2026-0891 بنسبة 96% وإضافة 1 نقطة إلى كوتا علاج العصب للطالب أحمد العتيبي',
  },
  {
    id: 'log-4',
    timestamp: '2026-08-25 14:00:20',
    actorId: 'user-supervisor-2',
    actorName: 'د. فهد القحطاني',
    actorRole: 'supervisor',
    action: 'REQUEST_CORRECTION',
    entityType: 'case',
    entityId: 'case-103',
    details: 'إعادة الحالة CLIN-2026-0893 للطالبة ريما الهذلي مع طلب توثيق أشعة ما بعد الجراحة وموعد فك الغرز',
  },
  {
    id: 'log-5',
    timestamp: '2026-08-27 15:30:10',
    actorId: 'user-supervisor-1',
    actorName: 'د. سارة الشمري',
    actorRole: 'supervisor',
    action: 'APPROVE_CASE',
    entityType: 'case',
    entityId: 'case-104',
    details: 'اعتماد جلسة تنظيف اللثة CLIN-2026-0894 بنسبة 92% للطالبة ريما الهذلي',
  },
];
