import { CurriculumLevel } from '../types';

export const STUDENT_CLINICAL_CURRICULUM: CurriculumLevel[] = [
  // ==========================================
  // 📘 المستوى الرابع (Level 4)
  // ==========================================
  {
    id: 'level4',
    nameAr: 'المستوى الرابع',
    nameEn: 'Level 4',
    academicYearLabel: 'السنة الإكلينيكية الرابعة - طب وجراحة الفم والأسنان',
    semesters: [
      // 🔹 الترم الأول (First Semester)
      {
        id: 'first',
        nameAr: 'الترم الأول',
        nameEn: 'First Semester',
        badge: 'الفصل الدراسي الأول',
        subjects: [
          {
            id: 'l4-s1-prostho',
            departmentKey: 'prosthodontics',
            nameAr: 'الاستعاضة السنية الثابتة',
            nameEn: 'Fixed Prosthodontics',
            totalCasesText: 'جسر خلفي واحد أو تاجين خلفيين',
            items: [
              {
                id: 'l4-s1-prostho-1',
                titleAr: '1 posterior Bridge OR 2 posterior crowns',
                titleEn: '1 Posterior Bridge OR 2 Posterior Crowns',
                targetCount: 1,
                unitLabel: 'حالة متكاملة',
                options: [
                  'خيار أ: جسر سنّي خلفي (1 Posterior Bridge)',
                  'خيار ب: تاجان خلفيان منفصلان (2 Posterior Crowns)',
                ],
              },
            ],
          },
          {
            id: 'l4-s1-operative',
            departmentKey: 'operative',
            nameAr: 'العلاج التحفظي وإصلاح الأسنان',
            nameEn: 'Operative Dentistry',
            totalCasesText: '11 حالة سريرية متنوعة التصنيفات',
            items: [
              {
                id: 'l4-s1-op-c1',
                titleAr: '3 Cases — Class I',
                titleEn: '3 Cases — Class I Restoration',
                targetCount: 3,
                unitLabel: 'حالات',
              },
              {
                id: 'l4-s1-op-c2',
                titleAr: '2 Cases — Class II (At least 1 Amalgam Restoration)',
                titleEn: '2 Cases — Class II (At least 1 Amalgam)',
                targetCount: 2,
                unitLabel: 'حالات',
                notes: ['يشترط أن تتضمن حالة واحدة على الأقل حشوة أملغم فضية (Amalgam).'],
              },
              {
                id: 'l4-s1-op-c3',
                titleAr: '2 Cases — Class III',
                titleEn: '2 Cases — Class III Restoration',
                targetCount: 2,
                unitLabel: 'حالات',
              },
              {
                id: 'l4-s1-op-c4',
                titleAr: '2 Cases — Class IV',
                titleEn: '2 Cases — Class IV Restoration',
                targetCount: 2,
                unitLabel: 'حالات',
              },
              {
                id: 'l4-s1-op-c5',
                titleAr: '2 Cases — Class V',
                titleEn: '2 Cases — Class V Restoration',
                targetCount: 2,
                unitLabel: 'حالات',
              },
            ],
          },
          {
            id: 'l4-s1-endo',
            departmentKey: 'endodontics',
            nameAr: 'علاج جذور الأسنان',
            nameEn: 'Endodontics',
            totalCasesText: '3 أسنان (أمامي وضواحك)',
            items: [
              {
                id: 'l4-s1-endo-opt',
                titleAr: 'متطلبات علاج الجذور (حسب الخيار المعتمد)',
                titleEn: 'Endodontic Clinical Requirement',
                targetCount: 3,
                unitLabel: 'أسنان معالجة',
                options: [
                  'الخيار الأول: 1 سن أمامي (Anterior) + 2 ضواحك (Premolars)',
                  'الخيار الثاني: 2 أسنان أمامية (Anterior) + 1 ضاحك (Premolar)',
                ],
              },
            ],
          },
          {
            id: 'l4-s1-perio',
            departmentKey: 'periodontics',
            nameAr: 'أمراض وجراحة اللثة',
            nameEn: 'Periodontics',
            hasNoRequirements: true,
            items: [],
            rulesAndNotes: ['لا يوجد متطلبات لسريريات هذا الترم (No requirements).'],
          },
          {
            id: 'l4-s1-surgery',
            departmentKey: 'oral_surgery',
            nameAr: 'جراحة الفم',
            nameEn: 'Oral Surgery',
            hasNoRequirements: true,
            items: [],
            rulesAndNotes: ['لا يوجد متطلبات لسريريات هذا الترم (No requirements).'],
          },
        ],
      },
      // 🔸 الترم الثاني (Second Semester)
      {
        id: 'second',
        nameAr: 'الترم الثاني',
        nameEn: 'Second Semester',
        badge: 'الفصل الدراسي الثاني',
        subjects: [
          {
            id: 'l4-s2-perio',
            departmentKey: 'periodontics',
            nameAr: 'أمراض وجراحة اللثة',
            nameEn: 'Periodontics',
            totalCasesText: 'إجمالي الحالات: 7 Cases',
            items: [
              {
                id: 'l4-s2-perio-ging',
                titleAr: '6 Gingivitis cases',
                titleEn: '6 Gingivitis Cases',
                targetCount: 6,
                unitLabel: 'حالات التهاب لثة',
              },
              {
                id: 'l4-s2-perio-perio',
                titleAr: '1 Periodontitis case (Diagnosis & Treatment)',
                titleEn: '1 Periodontitis case (Diagnosis & Treatment)',
                targetCount: 1,
                unitLabel: 'حالة التهاب دواعم السن',
              },
            ],
          },
          {
            id: 'l4-s2-prostho',
            departmentKey: 'prosthodontics',
            nameAr: 'الاستعاضة السنية الثابتة',
            nameEn: 'Fixed Prosthodontics',
            totalCasesText: 'جسر (أمامي/خلفي) أو تاجين',
            items: [
              {
                id: 'l4-s2-prostho-1',
                titleAr: '1 Bridge (Posterior OR Anterior) OR 2 Crowns',
                titleEn: '1 Bridge (Posterior OR Anterior) OR 2 Crowns',
                targetCount: 1,
                unitLabel: 'حالة تركيبات',
                options: [
                  'خيار أ: جسر سني خلفي أو أمامي (1 Bridge Posterior OR Anterior)',
                  'خيار ب: تاجان منفصلان (2 Crowns)',
                ],
              },
            ],
          },
          {
            id: 'l4-s2-surgery',
            departmentKey: 'oral_surgery',
            nameAr: 'جراحة الفم',
            nameEn: 'Oral Surgery',
            totalCasesText: 'إجمالي الحالات: 10 Cases',
            items: [
              {
                id: 'l4-s2-surg-10',
                titleAr: '10 حالات خلع جراحي / بسيط (10 Extraction Cases)',
                titleEn: '10 Cases — Extractions',
                targetCount: 10,
                unitLabel: 'حالات خلع',
              },
            ],
            rulesAndNotes: [
              'ملاحظة وقواعد: يمنع حالات الأسنان المغمورة / المجهزة للجراحة المعقدة (Impacted teeth are prohibited).',
            ],
          },
          {
            id: 'l4-s2-operative',
            departmentKey: 'operative',
            nameAr: 'العلاج التحفظي وإصلاح الأسنان',
            nameEn: 'Operative Dentistry',
            totalCasesText: '11 حالة سريرية',
            items: [
              {
                id: 'l4-s2-op-c1',
                titleAr: '3 Cases — Class I',
                titleEn: '3 Cases — Class I',
                targetCount: 3,
                unitLabel: 'حالات',
              },
              {
                id: 'l4-s2-op-c2',
                titleAr: '2 Cases — Class II (Must include 2 Amalgam Restorations on Molar or Premolar)',
                titleEn: '2 Cases — Class II (2 Amalgam Restorations on Molar or Premolar)',
                targetCount: 2,
                unitLabel: 'حالات',
                notes: ['يجب أن تشمل الحالتان حشوات أملغم فضية على الأرحاء أو الضواحك.'],
              },
              {
                id: 'l4-s2-op-c3',
                titleAr: '2 Cases — Class III',
                titleEn: '2 Cases — Class III',
                targetCount: 2,
                unitLabel: 'حالات',
              },
              {
                id: 'l4-s2-op-c4',
                titleAr: '2 Cases — Class IV',
                titleEn: '2 Cases — Class IV',
                targetCount: 2,
                unitLabel: 'حالات',
              },
              {
                id: 'l4-s2-op-c5',
                titleAr: '2 Cases — Class V',
                titleEn: '2 Cases — Class V',
                targetCount: 2,
                unitLabel: 'حالات',
              },
            ],
          },
          {
            id: 'l4-s2-endo',
            departmentKey: 'endodontics',
            nameAr: 'علاج جذور الأسنان',
            nameEn: 'Endodontics',
            totalCasesText: '3 أسنان (2 ضاحك + 1 رحى سفلية)',
            items: [
              {
                id: 'l4-s2-endo-premolars',
                titleAr: '2 Premolars',
                titleEn: '2 Premolars Root Canal Treatment',
                targetCount: 2,
                unitLabel: 'ضواحك',
              },
              {
                id: 'l4-s2-endo-molar',
                titleAr: '1 Lower Molar',
                titleEn: '1 Lower Molar Root Canal Treatment',
                targetCount: 1,
                unitLabel: 'رحى سفلية',
              },
            ],
          },
        ],
      },
    ],
  },

  // ==========================================
  // 📕 المستوى الخامس (Level 5)
  // ==========================================
  {
    id: 'level5',
    nameAr: 'المستوى الخامس',
    nameEn: 'Level 5',
    academicYearLabel: 'السنة الإكلينيكية الخامسة (امتياز / تخرج) - طب وجراحة الفم والأسنان',
    semesters: [
      // 🔹 الترم الأول (First Semester)
      {
        id: 'first',
        nameAr: 'الترم الأول',
        nameEn: 'First Semester',
        badge: 'الفصل الدراسي الأول',
        subjects: [
          {
            id: 'l5-s1-operative',
            departmentKey: 'operative',
            nameAr: 'العلاج التحفظي وإصلاح الأسنان',
            nameEn: 'Operative Dentistry',
            totalCasesText: '22 حالة متقدمة',
            items: [
              {
                id: 'l5-s1-op-c1',
                titleAr: '5 Cases — Class I',
                titleEn: '5 Cases — Class I',
                targetCount: 5,
                unitLabel: 'حالات',
              },
              {
                id: 'l5-s1-op-c2',
                titleAr: '4 Cases — Class II (2 Class II & 2 MOD)',
                titleEn: '4 Cases — Class II (2 Class II & 2 MOD)',
                targetCount: 4,
                unitLabel: 'حالات',
                notes: ['مقسمة بالتساوي: 2 كلاس II اعتيادي + 2 كلاس II من نوع MOD.'],
              },
              {
                id: 'l5-s1-op-c3',
                titleAr: '4 Cases — Class III',
                titleEn: '4 Cases — Class III',
                targetCount: 4,
                unitLabel: 'حالات',
              },
              {
                id: 'l5-s1-op-c4',
                titleAr: '3 Cases — Class IV',
                titleEn: '3 Cases — Class IV',
                targetCount: 3,
                unitLabel: 'حالات',
              },
              {
                id: 'l5-s1-op-c5',
                titleAr: '4 Cases — Class V',
                titleEn: '4 Cases — Class V',
                targetCount: 4,
                unitLabel: 'حالات',
              },
              {
                id: 'l5-s1-op-pins',
                titleAr: '1 Case — Build up with Pins (Posterior tooth)',
                titleEn: '1 Case — Build up with Pins (Posterior tooth)',
                targetCount: 1,
                unitLabel: 'حالة بناء بأوتاد دقيقة',
              },
              {
                id: 'l5-s1-op-veneer',
                titleAr: '1 Case — Direct Veneer',
                titleEn: '1 Case — Direct Composite Veneer',
                targetCount: 1,
                unitLabel: 'حالة فينير مباشر',
              },
            ],
          },
          {
            id: 'l5-s1-pedo',
            departmentKey: 'pedodontics',
            nameAr: 'طب أسنان الأطفال',
            nameEn: 'Pedodontics',
            totalCasesText: '12 إجراء سريري وقائي وعلاجي',
            items: [
              {
                id: 'l5-s1-pedo-ext',
                titleAr: '3 Extractions',
                titleEn: '3 Extractions (Primary teeth)',
                targetCount: 3,
                unitLabel: 'حالات خلع لبني',
              },
              {
                id: 'l5-s1-pedo-rest',
                titleAr: '3 Restorative Classes (One must be Class II)',
                titleEn: '3 Restorative Classes (One must be Class II)',
                targetCount: 3,
                unitLabel: 'حشوات أطفال',
                notes: ['يشترط أن تكون حالة واحدة على الأقل حشوة Class II.'],
              },
              {
                id: 'l5-s1-pedo-pulpo',
                titleAr: '2 Pulpotomies',
                titleEn: '2 Pulpotomies',
                targetCount: 2,
                unitLabel: 'حالات بتر لب',
              },
              {
                id: 'l5-s1-pedo-pulpec',
                titleAr: '1 Pulpectomy (خلال العام الدراسي كامل)',
                titleEn: '1 Pulpectomy (Throughout the entire academic year)',
                targetCount: 1,
                unitLabel: 'حالة استئصال لب سنوي',
                notes: ['يمكن إنجاز هذه الحالة في الترم الأول أو الثاني خلال العام الدراسي كاملاً.'],
              },
              {
                id: 'l5-s1-pedo-sealant',
                titleAr: '2 Fissure Sealants',
                titleEn: '2 Fissure Sealants',
                targetCount: 2,
                unitLabel: 'سادات شقوق وقائية',
              },
              {
                id: 'l5-s1-pedo-fluoride',
                titleAr: '2 Fluoride Applications',
                titleEn: '2 Fluoride Applications',
                targetCount: 2,
                unitLabel: 'تطبيقات فلورايد',
              },
            ],
          },
          {
            id: 'l5-s1-prostho',
            departmentKey: 'prosthodontics',
            nameAr: 'الاستعاضة السنية الثابتة',
            nameEn: 'Fixed Prosthodontics',
            totalCasesText: '1 Post & Core + (جسر 3 وحدات أو تاجين)',
            items: [
              {
                id: 'l5-s1-prostho-post',
                titleAr: '1 Post & Core',
                titleEn: '1 Post & Core Restoration',
                targetCount: 1,
                unitLabel: 'حالة وتد وقلب',
              },
              {
                id: 'l5-s1-prostho-bridge-crowns',
                titleAr: '1 Bridge (3-Unit) OR 2 Crowns',
                titleEn: '1 Bridge (3-Unit) OR 2 Crowns',
                targetCount: 1,
                unitLabel: 'تركيبة معتمدة',
                options: [
                  'خيار أ: جسر ثلاثي الوحدات (1 Bridge 3-Unit)',
                  'خيار ب: تاجان منفصلان (2 Crowns)',
                ],
              },
            ],
            conditions: [
              'في حالة الجسر (Bridge): يشترط أن يكون أحد الأسنان الداعمة (Abutment) قد تم عمل Post & Core له من قبل الطالب نفسه.',
              'في حالة التاجين (2 Crowns): يشترط أن يكون أحد الأسنان قد تم عمل Post & Core له من قبل الطالب نفسه.',
            ],
          },
          {
            id: 'l5-s1-surgery',
            departmentKey: 'oral_surgery',
            nameAr: 'جراحة الفم والفكين',
            nameEn: 'Maxillofacial Surgery',
            totalCasesText: 'إجمالي الحالات: 10 Cases',
            items: [
              {
                id: 'l5-s1-surg-10',
                titleAr: '10 حالات جراحة فم وفكين (10 Surgery Cases)',
                titleEn: '10 Maxillofacial Surgery Cases',
                targetCount: 10,
                unitLabel: 'حالات جراحة',
              },
            ],
            rulesAndNotes: [
              'ملاحظة وقواعد: يمنع حالات الأسنان اللبنية (Deciduous teeth) وحالات الأسنان المغمورة (Impacted teeth).',
            ],
          },
          {
            id: 'l5-s1-endo',
            departmentKey: 'endodontics',
            nameAr: 'علاج جذور الأسنان',
            nameEn: 'Endodontics',
            totalCasesText: '3 أسنان سفلية (أمامي + ضاحك + رحى)',
            items: [
              {
                id: 'l5-s1-endo-ant',
                titleAr: '1 Lower Anterior',
                titleEn: '1 Lower Anterior RCT',
                targetCount: 1,
                unitLabel: 'سن أمامي سفلي',
              },
              {
                id: 'l5-s1-endo-premolar',
                titleAr: '1 Lower Premolar',
                titleEn: '1 Lower Premolar RCT',
                targetCount: 1,
                unitLabel: 'ضاحك سفلي',
              },
              {
                id: 'l5-s1-endo-molar',
                titleAr: '1 Lower Molar',
                titleEn: '1 Lower Molar RCT',
                targetCount: 1,
                unitLabel: 'رحى سفلية',
              },
            ],
          },
          {
            id: 'l5-s1-perio',
            departmentKey: 'periodontics',
            nameAr: 'أمراض وجراحة اللثة',
            nameEn: 'Periodontics',
            totalCasesText: 'إجمالي الحالات: 7 Cases',
            items: [
              {
                id: 'l5-s1-perio-diag',
                titleAr: '1 Diagnosis case',
                titleEn: '1 Diagnosis case',
                targetCount: 1,
                unitLabel: 'حالة تشخيص كامل',
              },
              {
                id: 'l5-s1-perio-st1',
                titleAr: '2 Stage I cases',
                titleEn: '2 Stage I Periodontitis cases',
                targetCount: 2,
                unitLabel: 'حالات المرحلة الأولى',
              },
              {
                id: 'l5-s1-perio-st2',
                titleAr: '2 Stage II cases',
                titleEn: '2 Stage II Periodontitis cases',
                targetCount: 2,
                unitLabel: 'حالات المرحلة الثانية',
              },
              {
                id: 'l5-s1-perio-st3',
                titleAr: '2 Stage III cases',
                titleEn: '2 Stage III Periodontitis cases',
                targetCount: 2,
                unitLabel: 'حالات المرحلة الثالثة',
              },
            ],
          },
        ],
      },
      // 🔸 الترم الثاني (Second Semester)
      {
        id: 'second',
        nameAr: 'الترم الثاني',
        nameEn: 'Second Semester',
        badge: 'الفصل الدراسي الثاني',
        subjects: [
          {
            id: 'l5-s2-operative',
            departmentKey: 'operative',
            nameAr: 'العلاج التحفظي وإصلاح الأسنان',
            nameEn: 'Operative Dentistry',
            totalCasesText: '19 حالة سريرية تخصصية',
            items: [
              {
                id: 'l5-s2-op-c1',
                titleAr: '4 Cases — Class I (1 Amalgam + 3 Composite)',
                titleEn: '4 Cases — Class I (1 Amalgam + 3 Composite)',
                targetCount: 4,
                unitLabel: 'حالات',
                notes: ['موزعة إلى: 1 حشوة أملغم فضية + 3 حشوات كومبوزيت تجميلية.'],
              },
              {
                id: 'l5-s2-op-c2',
                titleAr: '4 Cases — Class II (2 Complex + 2 Compound - At least one Amalgam)',
                titleEn: '4 Cases — Class II (2 Complex + 2 Compound - At least 1 Amalgam)',
                targetCount: 4,
                unitLabel: 'حالات',
                notes: ['موزعة إلى: 2 معقدة (Complex) + 2 مركبة (Compound)، مع اشتراط أملغم واحدة على الأقل.'],
              },
              {
                id: 'l5-s2-op-c3',
                titleAr: '3 Cases — Class III',
                titleEn: '3 Cases — Class III',
                targetCount: 3,
                unitLabel: 'حالات',
              },
              {
                id: 'l5-s2-op-c4',
                titleAr: '2 Cases — Class IV',
                titleEn: '2 Cases — Class IV',
                targetCount: 2,
                unitLabel: 'حالات',
              },
              {
                id: 'l5-s2-op-c5',
                titleAr: '3 Cases — Class V',
                titleEn: '3 Cases — Class V',
                targetCount: 3,
                unitLabel: 'حالات',
              },
              {
                id: 'l5-s2-op-pins',
                titleAr: '1 Case — Build up with Pins (Posterior tooth)',
                titleEn: '1 Case — Build up with Pins (Posterior tooth)',
                targetCount: 1,
                unitLabel: 'حالة بناء وتد',
              },
              {
                id: 'l5-s2-op-veneer',
                titleAr: '1 Case — Direct Veneer (Anterior teeth - Class IV)',
                titleEn: '1 Case — Direct Veneer (Anterior teeth - Class IV)',
                targetCount: 1,
                unitLabel: 'حالة فينير أمامي',
              },
              {
                id: 'l5-s2-op-deep-caries-pulp',
                titleAr: 'إدارة التسوس العميق: 1 Case — Direct pulp capping OR Indirect pulp capping',
                titleEn: '1 Case — Direct or Indirect Pulp Capping (Management of Deep Caries)',
                targetCount: 1,
                unitLabel: 'تغطية لب السن',
                options: [
                  'خيار أ: تغطية اللب المباشرة (Direct Pulp Capping)',
                  'خيار ب: تغطية اللب غير المباشرة (Indirect Pulp Capping)',
                ],
              },
              {
                id: 'l5-s2-op-deep-caries-cusp',
                titleAr: 'إدارة التسوس العميق: 1 Case — Cusp capping for Amalgam restoration',
                titleEn: '1 Case — Cusp Capping for Amalgam Restoration',
                targetCount: 1,
                unitLabel: 'تغطية حدبة أملغم',
              },
            ],
          },
          {
            id: 'l5-s2-pedo',
            departmentKey: 'pedodontics',
            nameAr: 'طب أسنان الأطفال',
            nameEn: 'Pedodontics',
            totalCasesText: '11 إجراء سريري ووقائي متقدم',
            items: [
              {
                id: 'l5-s2-pedo-ext',
                titleAr: '3 Extractions',
                titleEn: '3 Extractions',
                targetCount: 3,
                unitLabel: 'حالات خلع',
              },
              {
                id: 'l5-s2-pedo-rest',
                titleAr: '3 Restorative Classes (One must be Class II)',
                titleEn: '3 Restorative Classes (One must be Class II)',
                targetCount: 3,
                unitLabel: 'حشوات أطفال',
                notes: ['يشترط أن تكون حالة واحدة على الأقل حشوة Class II.'],
              },
              {
                id: 'l5-s2-pedo-pulpo-ssc',
                titleAr: '2 Pulpotomies with 2 Stainless Steel Crowns (st.st crown)',
                titleEn: '2 Pulpotomies with 2 Stainless Steel Crowns (st.st crown)',
                targetCount: 2,
                unitLabel: 'بتر لب + تيجان ستانلس ستيل',
              },
              {
                id: 'l5-s2-pedo-pulpec',
                titleAr: '1 Pulpectomy (خلال العام الدراسي كامل)',
                titleEn: '1 Pulpectomy (Throughout the entire academic year)',
                targetCount: 1,
                unitLabel: 'استئصال لب سنوي',
                notes: ['تُحتسب خلال العام الدراسي كاملاً.'],
              },
              {
                id: 'l5-s2-pedo-sm-uni',
                titleAr: '1 Space Maintainer (Unilateral) (لكل طالب)',
                titleEn: '1 Space Maintainer (Unilateral) (Per student)',
                targetCount: 1,
                unitLabel: 'حافظ مسافة أحادي الجانب',
                notes: ['مطلوب كحالة فردية لكل طالب.'],
              },
              {
                id: 'l5-s2-pedo-sm-bi',
                titleAr: '1 Space Maintainer (Bilateral) (لكل طالبين)',
                titleEn: '1 Space Maintainer (Bilateral) (Per 2 students team)',
                targetCount: 1,
                unitLabel: 'حافظ مسافة ثنائي الجانب',
                notes: ['حالة مشتركة بين طالبين في المجموعة السريرية.'],
              },
            ],
          },
          {
            id: 'l5-s2-prostho',
            departmentKey: 'prosthodontics',
            nameAr: 'الاستعاضة السنية الثابتة',
            nameEn: 'Fixed Prosthodontics',
            totalCasesText: '1 Post & Core + (جسر 3 وحدات أو تاجين)',
            items: [
              {
                id: 'l5-s2-prostho-post',
                titleAr: '1 Post & Core',
                titleEn: '1 Post & Core Restoration',
                targetCount: 1,
                unitLabel: 'حالة وتد وقلب',
              },
              {
                id: 'l5-s2-prostho-bridge-crowns',
                titleAr: '1 Bridge (3-Unit) OR 2 Crowns',
                titleEn: '1 Bridge (3-Unit) OR 2 Crowns',
                targetCount: 1,
                unitLabel: 'تركيبة معتمدة',
                options: [
                  'خيار أ: جسر ثلاثي الوحدات (1 Bridge 3-Unit)',
                  'خيار ب: تاجان منفصلان (2 Crowns)',
                ],
              },
            ],
            conditions: [
              'في حالة الجسر (Bridge): يشترط أن يكون أحد الأسنان الداعمة (Abutment) قد تم عمل Post & Core له من قبل الطالب نفسه.',
              'في حالة التاجين (2 Crowns): يشترط أن يكون أحد الأسنان قد تم عمل Post & Core له من قبل الطالب نفسه.',
            ],
          },
          {
            id: 'l5-s2-surgery',
            departmentKey: 'oral_surgery',
            nameAr: 'جراحة الفم والفكين',
            nameEn: 'Maxillofacial Surgery',
            totalCasesText: 'إجمالي الحالات: 10 Cases',
            items: [
              {
                id: 'l5-s2-surg-10',
                titleAr: '10 حالات جراحة فم وفكين (10 Surgery Cases)',
                titleEn: '10 Maxillofacial Surgery Cases',
                targetCount: 10,
                unitLabel: 'حالات جراحة',
              },
            ],
            rulesAndNotes: [
              'ملاحظة وقواعد: يمنع حالات الأسنان اللبنية (Deciduous teeth) وحالات الأسنان المغمورة (Impacted teeth).',
            ],
          },
          {
            id: 'l5-s2-endo',
            departmentKey: 'endodontics',
            nameAr: 'علاج جذور الأسنان',
            nameEn: 'Endodontics',
            totalCasesText: '3 أسنان علوية (أمامي + ضاحك + رحى)',
            items: [
              {
                id: 'l5-s2-endo-ant',
                titleAr: '1 Upper Anterior',
                titleEn: '1 Upper Anterior RCT',
                targetCount: 1,
                unitLabel: 'سن أمامي علوي',
              },
              {
                id: 'l5-s2-endo-premolar',
                titleAr: '1 Upper Premolar',
                titleEn: '1 Upper Premolar RCT',
                targetCount: 1,
                unitLabel: 'ضاحك علوي',
              },
              {
                id: 'l5-s2-endo-molar',
                titleAr: '1 Upper Molar',
                titleEn: '1 Upper Molar RCT',
                targetCount: 1,
                unitLabel: 'رحى علوية',
              },
            ],
          },
          {
            id: 'l5-s2-perio',
            departmentKey: 'periodontics',
            nameAr: 'أمراض وجراحة اللثة',
            nameEn: 'Periodontics',
            totalCasesText: 'إجمالي الحالات: 7 Cases (6 غير جراحية + 1 جراحية)',
            items: [
              {
                id: 'l5-s2-perio-nonsurg',
                titleAr: '6 Non-surgical cases (Different stages of periodontitis)',
                titleEn: '6 Non-surgical cases (Different stages of periodontitis)',
                targetCount: 6,
                unitLabel: 'حالات غير جراحية لمراحل مختلفة',
              },
              {
                id: 'l5-s2-perio-surg',
                titleAr: '1 Surgical case (Crown lengthening, Depigmentation, or Gingivectomy)',
                titleEn: '1 Surgical case (Crown lengthening, Depigmentation, or Gingivectomy)',
                targetCount: 1,
                unitLabel: 'حالة جراحية معتمدة',
                options: [
                  'خيار أ: إطالة تاج السن جراحياً (Crown Lengthening)',
                  'خيار ب: إزالة تصبغات اللثة (Gingival Depigmentation)',
                  'خيار ج: استئصال اللثة الجراحي (Gingivectomy)',
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];
